### ISSUE TITLE
Can't spawn a fake player with LuckPerms installed.

### ISSUE THREAD

**Issue by FlamingCherry** [gnembon/fabric-carpet#1004]
Hello. I cannot spawn a fake player with the **/player Alex spawn** command if LuckPerms is installed on the server. When the command is executed, the message "An unexpected error occurred trying to execute that command" is displayed in the chat, and the console does not have any errors. How to fix this?

P.S. Minecraft 1.17.1, latest version of Carpet and latest version of LuckPerms.

**Comment by James103** [comment]
What text do you get in the tooltip when you hover over the red text saying "An unexpected error occurred trying to execute that command"? Can you please post of screenshot of you doing that?

**Comment by FlamingCherry** [comment]
> What text do you get in the tooltip when you hover over the red text saying "An unexpected error occurred trying to execute that command"? Can you please post of screenshot of you doing that?
When I hover over the red text, the tooltip just says "user".
https://prnt.sc/1bo9ii6

**Comment by James103** [comment]
I was going to suggest that you try reproducing this with [Why Did My Command Fail](https://github.com/ByMartrixx/wdmcf/tree/master) installed in order to (hopefully) print more debug information, however, that mod is incompatible with Carpet mod.

**Comment by FlamingCherry** [comment]
> I was going to suggest that you try reproducing this with [Why Did My Command Fail](https://github.com/ByMartrixx/wdmcf/tree/master) installed in order to (hopefully) print more debug information, however, that mod is incompatible with Carpet mod.
> 
> Alternatively, can you please try running the command `/script run run('player Alex spawn')` and posting a screenshot of the output?

"Why Did My Command Fail" not working at all with Carpet installed.
`net.fabricmc.loader.discovery.ModResolutionException: Found conflicting mods: wdmcf conflicts with {carpet @ [*]}
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:219) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~>        at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:216) ~[fabric-server-launch.jar:?]
        ... 12 more`

Script output: https://prnt.sc/1bofatx

I ran the command **/carpet superSecretSettings true** and now an exception appears in the console when I execute the command **/player Alex spawn**: https://hastebin.app/60f1207051a8e5001ddfe915

**Comment by James103** [comment]
Copied exception from paste:
```
[07:59:25] [Server thread/ERROR]: Command exception: /player Alex spawn
java.lang.NullPointerException: user
        at java.util.Objects.requireNonNull(Objects.java:233) ~[?:?]
        at me.lucko.luckperms.common.api.implementation.ApiPlayerAdapter.getUser(ApiPlayerAdapter.java:60) ~[LuckPerms-Fabric-5.3.51.jar:?]
        at eu.pb4.bof.mods.LuckPermsPlaceholders.lambda$register$0(LuckPermsPlaceholders.java:29) ~[box-of-placeholders-1.3.1+1.17.1.jar:?]
        at eu.pb4.placeholders.util.PlaceholderUtils.parsePlaceholderFromMap(PlaceholderUtils.java:227) ~[9d0c1b41-3862-44bd-bad1-2f94190bb22f.jar:?]  
        at eu.pb4.placeholders.util.PlaceholderUtils.recursivePlaceholderParsing(PlaceholderUtils.java:59) ~[9d0c1b41-3862-44bd-bad1-2f94190bb22f.jar:?]
        at eu.pb4.placeholders.PlaceholderAPI.parseText(PlaceholderAPI.java:44) ~[9d0c1b41-3862-44bd-bad1-2f94190bb22f.jar:?]
        at eu.pb4.styledplayerlist.config.Config.formatPlayerUsername(Config.java:62) ~[styledplayerlist-2.1.0.jar:?]
        at net.minecraft.class_3222.handler$bgc000$changePlayerListName(class_3222.java:7264) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_14206(class_3222.java) ~[intermediary-server.jar:?]
        at net.minecraft.class_2703.<init>(class_2703.java:28) ~[intermediary-server.jar:?]
        at net.minecraft.class_3225.method_14261(class_3225.java:69) ~[intermediary-server.jar:?]
        at net.minecraft.class_3222.method_32748(class_3222.java:1579) ~[intermediary-server.jar:?]
        at net.minecraft.class_3324.method_14570(class_3324.java:165) ~[intermediary-server.jar:?]
        at carpet.patches.EntityPlayerMPFake.createFake(EntityPlayerMPFake.java:65) ~[fabric-carpet-1.17.1-1.4.44+v210714.jar:?]
        at carpet.commands.PlayerCommand.spawn(PlayerCommand.java:289) ~[fabric-carpet-1.17.1-1.4.44+v210714.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[intermediary-server.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[intermediary-server.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:251) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_14370(class_3244.java:1222) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_31286(class_3244.java:1206) ~[intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12048(class_3244.java:1189) ~[intermediary-server.jar:?]
        at net.minecraft.class_2797.method_12115(class_2797.java:30) ~[intermediary-server.jar:?]
        at net.minecraft.class_2797.method_11054(class_2797.java:7) ~[intermediary-server.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-server.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-server.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zop000$modifiedRunLoop(MinecraftServer.java:4399) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by altrisi** [comment]
I'm almost sure the NPE with fake players was fixed in a recent version only available in their website (they don't update other sites often), will check again.

**Comment by FlamingCherry** [comment]
> I'm almost sure the NPE with fake players was fixed in a recent version only available in their website (they don't update other sites often), will check again. 

I get latest version from their website

**Comment by altrisi** [comment]
Is this still an issue? I believe I've read from people using LuckPerms with carpet players without issues, but I may be wrong. I'm closing this issue, but if it's still happening feel free to comment and it can be reopened, or make a new issue.
