### ISSUE TITLE
Server crashes when running command /spawn tracking start 

### ISSUE THREAD

**Issue by Killakilla2** [gnembon/fabric-carpet#1052]
![image](https://user-images.githubusercontent.com/88597528/128613495-945b703e-f8d4-4615-8cb4-20f6001bb58a.png)

This creates a ticking world problem and per Apex hosting staff "This seems like an internal issue with the carpet mod, so this should be reported to the developers"

Server is fabric 1.17.1 and using fabric-carpet-1.17.1-1.4.44+v210714.jar

**Comment by Killakilla2** [comment]
edit.  when using 1.4.43 the server does not crash using this command

**Comment by gnembon** [comment]
The serve shouldn't crash, but that's an an odd situation to happen. I didn't fix the problem, but fix the crash for now. More info (in terms of what you were measuring and how) would be helpful here.

**Comment by Killakilla2** [comment]
server ran the commnad fin yesterday but then today when I ran the command again it crashed on the 1.4.43.  In the first crash scenario i was AFK at a single witch hut farm with 3 spawn platforms.  The second time I was AFK at a raid farm but had not started the raid I was lookign to see the data of othe mobs spawning to see how well i spawn proofed the areas.

9:52:10] [Server thread/INFO]: [KillaKilla: Spawning tracking started.]
[09:52:13] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:895) ~[intermediary-server.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:335) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zke000$modifiedRunLoop(MinecraftServer.java:4390) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Long.longValue()" because the return value of "java.util.HashMap.get(Object)" is null
	at carpet.utils.SpawnReporter.registerSpawn(SpawnReporter.java:89) ~[fabric-carpet-1.17.1-1.4.43+v210706.jar:?]
	at net.minecraft.class_1948.redirect$zmo000$spawnEntity(class_1948.java:1262) ~[intermediary-server.jar:?]
	at net.minecraft.class_1948.method_24930(class_1948.java:286) ~[intermediary-server.jar:?]
	at net.minecraft.class_1948.method_8663(class_1948.java:199) ~[intermediary-server.jar:?]
	at net.minecraft.class_1948.redirect$zmo000$spawnMultipleTimes(class_1948.java:1310) ~[intermediary-server.jar:?]
	at net.minecraft.class_1948.method_27821(class_1948.java:187) ~[intermediary-server.jar:?]
	at net.minecraft.class_3215.method_20801(class_3215.java:368) ~[intermediary-server.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at net.minecraft.class_3215.method_14161(class_3215.java:355) ~[intermediary-server.jar:?]
	at net.minecraft.class_3215.method_12127(class_3215.java:324) ~[intermediary-server.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:372) ~[intermediary-server.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891) ~[intermediary-server.jar:?]
	... 6 more
[09:52:13] [Server thread/ERROR]: This crash report has been saved to: /home/minecraft/multicraft/servers/server786762/./crash-reports/crash-2021-08-09_09.52.13-server.txt
