### ISSUE TITLE
Error when using spawn rate or spawn mobcaps for water_ambient

### ISSUE THREAD

**Issue by Hakatsc** [gnembon/fabric-carpet#1073]
Just like the title i cant change water ambient mobcap or spawn rates but can change others. I also tried it with new world and without any other mods still same result.
![2021-08-22_14 59 51](https://user-images.githubusercontent.com/78194308/130354354-066be169-4572-4e0a-8db7-aa2ae5639a55.png)

**Comment by James103** [comment]
What Minecraft version are you using?
Can you please try running `/carpet superSecretSetting true` before reproducing this? What log output do you get (especially the exception)?

**Comment by Hakatsc** [comment]
I think i know what happened in my language(Turkish) uppercase i is İ which is what fabric is looking for and failing to find i also cant use WATER_AMBIENT in command


[01:46:18] [Server thread/ERROR]: Command exception: /spawn rates water_ambient 0
java.lang.IllegalArgumentException: No enum constant net.minecraft.class_1311.WATER_AMBİENT
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at net.minecraft.class_1311.valueOf(class_1311.java:10) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at carpet.commands.SpawnCommand.getCategory(SpawnCommand.java:113) ~[fabric-carpet-1.17.1-1.4.45+v210811%20(1).jar:?]
	at carpet.commands.SpawnCommand.setSpawnRates(SpawnCommand.java:246) ~[fabric-carpet-1.17.1-1.4.45+v210811%20(1).jar:?]
	at carpet.commands.SpawnCommand.lambda$register$17(SpawnCommand.java:86) ~[fabric-carpet-1.17.1-1.4.45+v210811%20(1).jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:251) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3244.method_14370(class_3244.java:1222) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3244.method_31286(class_3244.java:1206) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3244.method_12048(class_3244.java:1189) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_2797.method_12115(class_2797.java:30) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_2797.method_11054(class_2797.java:7) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zpg000$modifiedRunLoop(MinecraftServer.java:4399) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-fabric-loader-0.11.6-1.17.1.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
