### ISSUE TITLE
Failed to store chunk errors

### ISSUE THREAD

**Issue by ezrareeves** [gnembon/fabric-carpet#1194]
After upgrading my 1.17.1 world to 1.18 I started getting these errors even if nobody is online.
This is from spawn chunks, however if I fly around it also happens in newly explored chunks occasionally.

[16:44:23] [IO-Worker-54/ERROR]: Failed to store chunk [1, -2]
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1597) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1620) ~[?:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:163) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:476) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:165) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_2499.method_10713(class_2499.java:128) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:476) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:165) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_2499.method_10713(class_2499.java:128) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_2487.method_10555(class_2487.java:476) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_2487.method_10713(class_2487.java:165) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_2507.method_10631(class_2507.java:118) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_2507.method_10628(class_2507.java:83) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_2867.method_23726(class_2867.java:79) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_4698.method_23701(class_4698.java:174) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_4698.method_23719(class_4698.java:164) ~[intermediary-server-1.18.jar:?]
	at net.minecraft.class_3847$class_3907.run(class_3847.java:59) [intermediary-server-1.18.jar:?]
	at net.minecraft.class_3846.method_16907(class_3846.java:91) [intermediary-server-1.18.jar:?]
	at net.minecraft.class_3846.method_16900(class_3846.java:146) [intermediary-server-1.18.jar:?]
	at net.minecraft.class_3846.run(class_3846.java:102) [intermediary-server-1.18.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by altrisi** [comment]
Does it happen without Carpet?

**Comment by ezrareeves** [comment]
I started it without carpet and it does still happen :(

**Comment by ezrareeves** [comment]
Opened a ticket with fabric

**Comment by James103** [comment]
See: FabricMC/fabric#1875

**Comment by gnembon** [comment]
should be fixed in vanilla for 1.18.1 real soon
