### ISSUE TITLE
SPAWNCHUNKSSIZE TO 11 FAILS TO EXECUTE

### ISSUE THREAD

**Issue by Lokemol** [gnembon/fabric-carpet#1213]
So, what happens in this error, is that, once you've SetDefault 0 spawnchunks size, when you try to set it to 11 again, it will give an error, not able to execute that command, the solution that was given to me by altrisi, was to remove the SetDefaul from the Carpet.conf, that seemed to fix it, but as of now, if you setdefault 0, it will sometimes not allow you to go back to 11, from in-game

https://imgur.com/a/npZwFTp9(image with error code) the last part can't be read, but it says "is null"

**Comment by James103** [comment]
Can you please try running the following commands in order and post the resulting log output?
```mcfunction
carpet superSecretSetting true
carpet spawnChunksSize 11
```

**Comment by koopaboopa** [comment]
I encountered a similar issue. For me, this issue seems to only happen when changing between zero and nonzero spawnChunksSize while in close proximity to the world spawn. If I'm far away from spawn chunks, /carpet spawnChunksSize runs successfully.

I ran the commands James103 suggested. Here's my output:
```
[17:34:36] [Server thread/INFO]: [Zomb44: superSecretSetting: true, [change permanently?]]
[17:34:36] [Render thread/INFO]: [CHAT] superSecretSetting: true, [change permanently?]
[17:34:45] [Render thread/INFO]: [CHAT] [Debug]: Chunk borders: shown
[17:34:55] [Server thread/ERROR]: Command exception: /carpet spawnChunksSize 11
java.lang.NullPointerException: Cannot read field "field_14025" because "â˜ƒ" is null
	at net.minecraft.class_3228.method_14285(class_3228.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_3228.compareTo(class_3228.java:5) ~[client-intermediary.jar:?]
	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:52) ~[?:?]
	at java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47) ~[?:?]
	at java.util.Arrays.binarySearch0(Arrays.java:2340) ~[?:?]
	at java.util.Arrays.binarySearch(Arrays.java:2325) ~[?:?]
	at net.minecraft.class_4706.method_23869(class_4706.java:56) ~[client-intermediary.jar:?]
	at net.minecraft.class_4706.add(class_4706.java:70) ~[client-intermediary.jar:?]
	at net.minecraft.class_3204.changeSpawnChunks(class_3204.java:1544) ~[client-intermediary.jar:?]
	at carpet.utils.SpawnChunks.changeSpawnChunks(SpawnChunks.java:14) ~[fabric-carpet-1.17.1-1.4.56+v211130.jar:?]
	at carpet.CarpetSettings$ChangeSpawnChunksValidator.changeSpawnSize(CarpetSettings.java:695) ~[fabric-carpet-1.17.1-1.4.56+v211130.jar:?]
	at carpet.CarpetSettings$ChangeSpawnChunksValidator.validate(CarpetSettings.java:714) ~[fabric-carpet-1.17.1-1.4.56+v211130.jar:?]
	at carpet.CarpetSettings$ChangeSpawnChunksValidator.validate(CarpetSettings.java:685) ~[fabric-carpet-1.17.1-1.4.56+v211130.jar:?]
	at carpet.settings.ParsedRule.set(ParsedRule.java:161) ~[fabric-carpet-1.17.1-1.4.56+v211130.jar:?]
	at carpet.settings.ParsedRule.set(ParsedRule.java:137) ~[fabric-carpet-1.17.1-1.4.56+v211130.jar:?]
	at carpet.settings.SettingsManager.setRule(SettingsManager.java:668) ~[fabric-carpet-1.17.1-1.4.56+v211130.jar:?]
	at carpet.settings.SettingsManager.lambda$registerCommand$34(SettingsManager.java:624) ~[fabric-carpet-1.17.1-1.4.56+v211130.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:251) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_14370(class_3244.java:1222) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_31286(class_3244.java:1206) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12048(class_3244.java:1189) ~[client-intermediary.jar:?]
	at net.minecraft.class_2797.method_12115(class_2797.java:30) ~[client-intermediary.jar:?]
	at net.minecraft.class_2797.method_11054(class_2797.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:788) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:770) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:749) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbe000$modifiedRunLoop(MinecraftServer.java:2899) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[17:34:55] [Render thread/INFO]: [CHAT] An unexpected error occurred trying to execute that command
Clipboard copy at: 12 Dec 2021 17:35:00 -0500
Clipboard copy at: 12 Dec 2021 17:43:06 -0500

```
