### ISSUE TITLE
Crash out of the blue with lithium

### ISSUE THREAD

**Issue by Justsnoopy30** [gnembon/fabric-carpet#1217]
Lithium author said this is an incompatibility on carpet's side to fix with latest lithium 0.7.6 for mc 1.18.1.
Log: 
`[20:20:37] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:883) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbk000$modifiedRunLoop(MinecraftServer.java:2856) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoClassDefFoundError: me/jellysquid/mods/lithium/common/hopper/InventoryHelper
	at net.minecraft.class_1703.handler$ben000$getFastOutputStrength(me/jellysquid/mods/lithium/mixin/block/hopper/ScreenHandlerMixin.java [lithium.mixins.json]:17) ~[server-intermediary.jar:?]
	at net.minecraft.class_1703.method_7618(class_1703.java:739) ~[server-intermediary.jar:?]
	at net.minecraft.class_1693.method_7525(class_1693.java:196) ~[server-intermediary.jar:?]
	at net.minecraft.class_1688.method_7513(class_1688.java:563) ~[server-intermediary.jar:?]
	at net.minecraft.class_1688.method_5773(class_1688.java:346) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:699) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:487) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:360) ~[server-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:328) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.redirect$zik000$fixUpdateSuppressionCrashTick(carpet/mixins/MinecraftServer_updateSuppressionCrashFixMixin.java [carpet.mixins.json]:31) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbk000$modifiedRunLoop(carpet/mixins/MinecraftServer_tickspeedMixin.java [carpet.mixins.json]:137) ~[server-intermediary.jar:?]
	... 3 more
Caused by: java.lang.ClassNotFoundException: me.jellysquid.mods.lithium.common.hopper.InventoryHelper
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.12.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.minecraft.class_1703.handler$ben000$getFastOutputStrength(me/jellysquid/mods/lithium/mixin/block/hopper/ScreenHandlerMixin.java [lithium.mixins.json]:17) ~[server-intermediary.jar:?]
	at net.minecraft.class_1703.method_7618(class_1703.java:739) ~[server-intermediary.jar:?]
	at net.minecraft.class_1693.method_7525(class_1693.java:196) ~[server-intermediary.jar:?]
	at net.minecraft.class_1688.method_7513(class_1688.java:563) ~[server-intermediary.jar:?]
	at net.minecraft.class_1688.method_5773(class_1688.java:346) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:699) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:487) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:360) ~[server-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:328) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.redirect$zik000$fixUpdateSuppressionCrashTick(carpet/mixins/MinecraftServer_updateSuppressionCrashFixMixin.java [carpet.mixins.json]:31) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:324) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbk000$modifiedRunLoop(carpet/mixins/MinecraftServer_tickspeedMixin.java [carpet.mixins.json]:137) ~[server-intermediary.jar:?]
	... 3 more`

**Comment by altrisi** [comment]
I may be stupid, but I can't see how Carpet could be causing this. There's no reference to it in the stack (other than the wrap around tick for catching update suppression catches, that's literally just that), and the exception is a NoClassDefFoundError, that I don't think can really be caused from a mod (other than by maybe overloading the stack so it errors on load, but that's not the case here). If you (or anyone) has any better insight on this, more information would be appreciated.

Properly formatted stacktrace for anyone looking at this later: https://cdn.discordapp.com/attachments/919693475316924446/920520536747032607/message.txt

**Comment by altrisi** [comment]
I'm closing this issue as there's been no response in months, feel free to comment if it's still an issue and it can be reopened, or make a new issue.
