### ISSUE TITLE
How to bypass whitelist when adding bot players?

### ISSUE THREAD

**Issue by Power-tile** [gnembon/fabric-carpet#1285]
I am running a server with a strict whitelist + offline player password requests since there are several offline players. I just finished the auth setup and found I cannot add bots to the world (gives an `An unexpected error occurred trying to execute the command`). How can I configure the server/mod so that adding bots bypass whitelist?

**Comment by James103** [comment]
Firstly, can you please try the following?
1. `carpet superSecretSetting true`
2. `player 111 spawn` (replace 111 with the name of the bot that you were trying to spawn)
3. Post the resulting server log output here.

**Comment by Power-tile** [comment]
@James103 The server backend gives this exception:
```
[Server] java.lang.NullPointerException: Cannot invoke "io.netty.channel.Channel.attr(io.netty.util.AttributeKey)" because the return value of "net.kyori.adventure.platform.fabric.impl.accessor.ConnectionAccess.getChannel()" is null
[Server]        at net.minecraft.class_3244.handler$zzg000$adventure$initTracking(class_3244.java:2162) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3244.<init>(class_3244.java:202) ~[server-intermediary.jar:?]
[Server]        at carpet.patches.NetHandlerPlayServerFake.<init>(NetHandlerPlayServerFake.java:15) ~[fabric-carpet-1.18-1.4.56+v211130.jar:?]
[Server]        at net.minecraft.class_3324.redirect$zde000$replaceNetworkHandler(class_3324.java:1977) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3324.method_14570(class_3324.java:169) ~[server-intermediary.jar:?]
[Server]        at carpet.patches.EntityPlayerMPFake.createFake(EntityPlayerMPFake.java:65) ~[fabric-carpet-1.18-1.4.56+v211130.jar:?]
[Server]        at carpet.commands.PlayerCommand.spawn(PlayerCommand.java:316) ~[fabric-carpet-1.18-1.4.56+v211130.jar:?]
[Server]        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
[Server]        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:177) ~[brigadier-1.0.18.jar:?]
[Server]        at net.minecraft.class_2170.method_9249(class_2170.java:262) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3244.method_14370(class_3244.java:1229) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3244.method_31286(class_3244.java:1213) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3244.method_12048(class_3244.java:1196) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2797.method_12115(class_2797.java:30) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2797.method_11054(class_2797.java:7) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:741) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.handler$zbn000$modifiedRunLoop(MinecraftServer.java:3365) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:663) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
[Server]        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Power-tile** [comment]
Found the same problem [here](https://github.com/gnembon/fabric-carpet/pull/1235). Updating carpet solves the issue.
