### ISSUE TITLE
Crash after finishing an entity profiling session

### ISSUE THREAD

**Issue by altrisi** [gnembon/fabric-carpet#1305]
Happened after finishing an entity profiling session. Had a debugger open, though for some reason it pointed at a different location so I couldn't gather any useful information, all I can say is that `CarpetProfiler.SECTION_STATS` was empty. I hadn't made any code changes yet.

Running on the 1.4.59 test source.

```java
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.accept(SortedOps.java:369)
	at it.unimi.dsi.fastutil.objects.Object2LongOpenHashMap$EntrySpliterator.acceptOnIndex(Object2LongOpenHashMap.java:1009)
	at it.unimi.dsi.fastutil.objects.Object2LongOpenHashMap$EntrySpliterator.acceptOnIndex(Object2LongOpenHashMap.java:991)
	at it.unimi.dsi.fastutil.objects.Object2LongOpenHashMap$MapSpliterator.forEachRemaining(Object2LongOpenHashMap.java:933)
	at it.unimi.dsi.fastutil.objects.Object2LongOpenHashMap$EntrySpliterator.forEachRemaining(Object2LongOpenHashMap.java:991)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at carpet.utils.CarpetProfiler.finalize_tick_report_for_entities(CarpetProfiler.java:303)
	at carpet.utils.CarpetProfiler.finalize_tick_report(CarpetProfiler.java:173)
	at carpet.utils.CarpetProfiler.end_tick_profiling(CarpetProfiler.java:164)
	at net.minecraft.server.MinecraftServer.handler$zbe000$stopAsync(MinecraftServer.java:3115)
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:760)
	at net.minecraft.server.MinecraftServer.handler$zbe000$modifiedRunLoop(MinecraftServer.java:3012)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:259)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by altrisi** [comment]
Forgot to mention, doesn't always happen.
