### ISSUE TITLE
Crash when using `/log projectiles` in 1.19

### ISSUE THREAD

**Issue by WRTY1** [gnembon/fabric-carpet#1545]
The crash report says the crash caused by `java.lang.ClassCastException`.

**Comment by WRTY1** [comment]
This is one part of **latest.log**

```
[19:35:17] Gestbod subscribed to projectiles.
[19:35:21] [Server thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[19:35:21] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:98) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zff000$modifiedRunLoop(MinecraftServer.java:3380) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class [Lnet.minecraft.class_2561; cannot be cast to class [Lnet.minecraft.class_5250; ([Lnet.minecraft.class_2561; and [Lnet.minecraft.class_5250; are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4c70fda8)
	at carpet.logging.logHelpers.TrajectoryLogHelper.handler$bao000$projectileLoggerEnhance(TrajectoryLogHelper.java:603) ~[fabric-carpet-1.19-1.4.79+v220607.jar:?]
	at carpet.logging.logHelpers.TrajectoryLogHelper.lambda$onFinish$0(TrajectoryLogHelper.java:75) ~[fabric-carpet-1.19-1.4.79+v220607.jar:?]
	at carpet.logging.Logger.log(Logger.java:170) ~[fabric-carpet-1.19-1.4.79+v220607.jar:?]
	at carpet.logging.logHelpers.TrajectoryLogHelper.onFinish(TrajectoryLogHelper.java:41) ~[fabric-carpet-1.19-1.4.79+v220607.jar:?]
	at net.minecraft.class_1682.method_5650(class_1682.java:540) ~[client-intermediary.jar:?]
	at net.minecraft.class_1297.method_31472(class_1297.java:371) ~[client-intermediary.jar:?]
	at net.minecraft.class_1684.method_7488(class_1684.java:74) ~[client-intermediary.jar:?]
	at net.minecraft.class_1682.method_5773(class_1682.java:65) ~[client-intermediary.jar:?]
	at net.minecraft.class_1684.method_5773(class_1684.java:84) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:711) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:466) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:370) ~[client-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:338) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[client-intermediary.jar:?]
	... 6 more
```

**Comment by WRTY1** [comment]
This is one part of **crash-report**

```
---- Minecraft Crash Report ----
// My bad.

Time: 2022/9/15 下午7:35
Description: Ticking entity

java.lang.ClassCastException: class [Lnet.minecraft.class_2561; cannot be cast to class [Lnet.minecraft.class_5250; ([Lnet.minecraft.class_2561; and [Lnet.minecraft.class_5250; are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @4c70fda8)
	at carpet.logging.logHelpers.TrajectoryLogHelper.handler$bao000$projectileLoggerEnhance(TrajectoryLogHelper.java:603)
	at carpet.logging.logHelpers.TrajectoryLogHelper.lambda$onFinish$0(TrajectoryLogHelper.java:75)
	at carpet.logging.Logger.log(Logger.java:170)
	at carpet.logging.logHelpers.TrajectoryLogHelper.onFinish(TrajectoryLogHelper.java:41)
	at net.minecraft.class_1682.method_5650(class_1682.java:540)
	at net.minecraft.class_1297.method_31472(class_1297.java:371)
	at net.minecraft.class_1684.method_7488(class_1684.java:74)
	at net.minecraft.class_1682.method_5773(class_1682.java:65)
	at net.minecraft.class_1684.method_5773(class_1684.java:84)
	at net.minecraft.class_3218.method_18762(class_3218.java:711)
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:370)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:338)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.handler$zff000$modifiedRunLoop(MinecraftServer.java:3380)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
```
-- Entity being ticked --
Details:
	Entity Type: minecraft:ender_pearl (net.minecraft.class_1684)
	Entity ID: 7
	Entity Name: 掷出的末影珍珠
	Entity's Exact location: -2.01, -61.92, 15.15
	Entity's Block location: World: (-3,-62,15), Section: (at 13,2,15 in -1,-4,0; chunk contains blocks -16,-64,0 to -1,319,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: -0.42, -2.00, 0.36
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:466)
	at net.minecraft.class_3218.method_31420(class_3218.java:370)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:338)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819)
	at net.minecraft.class_1132.method_3748(class_1132.java:98)
	at net.minecraft.server.MinecraftServer.handler$zff000$modifiedRunLoop(MinecraftServer.java:3380)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
```

**Comment by altrisi** [comment]
This is caused by another modifying carpet's logger, IIRC Carpet TIS Addition.
