### ISSUE TITLE
Cant spawn fake players.

### ISSUE THREAD

**Issue by Zyald** [gnembon/fabric-carpet#1602]
Whenver i do /player xxx spawn, an error comes up as "An unexpected error occurred trying to execute that command"
idk what to do

**Comment by James103** [comment]
The exception should have been logged to both the console (if there's one) and the latest.log. Will you please attach that latest.log file after exiting the game?

**Comment by Zyald** [comment]
thank you for the quick responses,
[latest.log](https://github.com/gnembon/fabric-carpet/files/10180116/latest.log)

**Comment by Zyald** [comment]
Also, i did the command at the very end of it

**Comment by Zyald** [comment]
> The exception should have been logged to both the console (if there's one) and the latest.log. Will you please attach that latest.log file after exiting the game?

it might be all my mods but it would still be nice to know what mods it is

**Comment by Sebas-Re** [comment]
Same here (server log): https://paste.corebot.dev/oquxonifej.bash

**Comment by James103** [comment]
<details>

<summary> Exception from the paste </summary>

```
player test28372 spawn
[22:49:41] [Server thread/INFO]: test28372[local] logged in with entity id 1218471 at (298.0, 70.0, -716.0)
[22:49:41] [Server thread/INFO]: [Essential Commands] Loading PlayerData for player with uuid 'c4e92eea-ec2a-3ae8-bb48-c9937918dc26'.
[22:49:41] [Server thread/INFO]: Sending server config values to client
[22:49:42] [Server thread/ERROR]: Command exception: /player test28372 spawn
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes
at net.minecraft.class_2658.<init(class_2658.java:39) ~[server-intermediary.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerNetworkingImpl.createPlayC2SPacket(ServerNetworkingImpl.java:536) ~[fabric-networking-api-v1-1.2.10+10eb22f490-d428db345cee8f65.jar:?]
at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.createS2CPacket(ServerPlayNetworking.java:211) ~[fabric-networking-api-v1-1.2.10+10eb22f490-d428db345cee8f65.jar:?]
at net.fabricmc.fabric.api.networking.v1.ServerPlayNetworking.send(ServerPlayNetworking.java:250) ~[fabric-networking-api-v1-1.2.10+10eb22f490-d428db345cee8f65.jar:?]
at net.fabricmc.fabric.impl.registry.sync.packet.RegistryPacketHandler.sendPacket(RegistryPacketHandler.java:52) ~[fabric-registry-sync-v0-0.9.31+9244241690-e6f873231068b81a.jar:?]
at net.fabricmc.fabric.impl.registry.sync.packet.NbtRegistryPacketHandler.sendPacket(NbtRegistryPacketHandler.java:52) ~[fabric-registry-sync-v0-0.9.31+9244241690-e6f873231068b81a.jar:?]
at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.sendPacket(RegistrySyncManager.java:96) ~[fabric-registry-sync-v0-0.9.31+9244241690-e6f873231068b81a.jar:?]
at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.sendPacket(RegistrySyncManager.java:88) ~[fabric-registry-sync-v0-0.9.31+9244241690-e6f873231068b81a.jar:?]
at net.fabricmc.fabric.impl.registry.sync.FabricRegistryInit.lambda$onInitialize$0(FabricRegistryInit.java:30) ~[fabric-registry-sync-v0-0.9.31+9244241690-e6f873231068b81a.jar:?]
at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.2.10+10eb22f490-d428db345cee8f65.jar:?]
at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:65) ~[fabric-networking-api-v1-1.2.10+10eb22f490-d428db345cee8f65.jar:?]
at net.minecraft.class_3324.handler$fcm000$handlePlayerConnection(class_3324.java:13013) ~[server-intermediary.jar:?]
at net.minecraft.class_3324.method_14570(class_3324.java:200) ~[server-intermediary.jar:?]
at carpet.patches.EntityPlayerMPFake.createFake(EntityPlayerMPFake.java:67) ~[fabric-carpet-1.19.2-1.4.84+v221018.jar:?]
at carpet.commands.PlayerCommand.spawn(PlayerCommand.java:320) ~[fabric-carpet-1.19.2-1.4.84+v221018.jar:?]
at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
at net.minecraft.class_2170.redirect$zoi000$performCommand(class_2170.java:545) ~[server-intermediary.jar:?]
at net.minecraft.class_2170.method_9249(class_2170.java:271) ~[server-intermediary.jar:?]
at net.minecraft.class_2170.method_44252(class_2170.java:264) ~[server-intermediary.jar:?]
at net.minecraft.class_3176.method_13941(class_3176.java:305) ~[server-intermediary.jar:?]
at net.minecraft.class_3176.method_3813(class_3176.java:290) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.handler$cje000$modifiedRunLoop(MinecraftServer.java:7885) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
[22:49:42] [Server thread/INFO]: An unexpected error occurred trying to execute that command
```

</details>

**Comment by Sebas-Re** [comment]
> Exception from the paste

Thank you very much, I was trying to do that on the phone and couldn't find a way lol

**Comment by silnarm** [comment]
@Zyald  @Sebas-Re

This is a fabric bug, and happens on account of the number of mods you are using and (more correctly) that they are adding so much content to the game. Fabric is sending the registries to the client and is using a `ClientboundCustomPayloadPacket` to do so, which is limited to 1MiB.

There are many related issues on their tracker, they even have a label `registry-sync` for such problems, I was unable to find one that matches this exactly, but did not dig very deep. You may wish to start a discussion over at https://github.com/FabricMC/fabric/discussions to see if it is known and/or planned to be fixed.

So, it is your mods, but probably not one specifically causing it (unless one in particular is adding all the new content).

**Comment by altrisi** [comment]
For those that it's an exception of packet size, I'm quite sure there's a mod to increment the limits, though it's strange it'd only happen when spawning carpet players (unless this is singleplayer maybe?)

**Comment by altrisi** [comment]
Going to close this as resolved, though if it happens again please open a new issue, I'd like to find why we are triggering that path with fake players that for some reason doesn't happen with regular players (because some of those packets could even be skipped for fakes if they get too problematic)
