### ISSUE TITLE
Polygon shape broken on servers

### ISSUE THREAD

**Issue by vlad2305m** [gnembon/fabric-carpet#1641]
`/script run draw_shape('polygon',20,{'points'->[[0,100,0],[0,100,1],[1,100,1]]})`
works in singleplayer (returns true and shows the polygon), but gives no output at all on servers. `fabric-carpet-1.19.3-1.4.93+v221230`

**Comment by James103** [comment]
Do you have Carpet mod installed on both the server **and client**?

**Comment by vlad2305m** [comment]
```
[20:39:01] [Server thread/ERROR] (carpet) Unexpected exception while running Scarpet code
 java.lang.RuntimeException: Cannot load class com.mojang.blaze3d.vertex.VertexFormat$Mode in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at carpet.script.utils.ShapeDispatcher$Polyface.init(ShapeDispatcher.java:918) ~[main/:?]
	at carpet.script.utils.ShapeDispatcher$ExpiringShape.fromOptions(ShapeDispatcher.java:321) ~[main/:?]
	at carpet.script.utils.ShapeDispatcher$ExpiringShape.lambda$creator$0(ShapeDispatcher.java:276) ~[main/:?]
	at carpet.script.utils.ShapeDispatcher.create(ShapeDispatcher.java:219) ~[main/:?]
	at carpet.script.utils.ShapeDispatcher.fromFunctionArgs(ShapeDispatcher.java:131) ~[main/:?]
	at carpet.script.api.Auxiliary.lambda$apply$8(Auxiliary.java:334) ~[main/:?]
	at carpet.script.Expression$17.lazyEval(Expression.java:605) ~[main/:?]
	at carpet.script.Expression.lambda$extractOp$20(Expression.java:1360) ~[main/:?]
	at carpet.script.Expression.evalValue(Expression.java:946) ~[main/:?]
	at carpet.script.Expression.eval(Expression.java:939) ~[main/:?]
	at carpet.script.CarpetExpression.lambda$scriptRunCommand$13(CarpetExpression.java:111) ~[main/:?]
	at carpet.script.utils.GlocalFlag.whileValueReturn(GlocalFlag.java:42) ~[main/:?]
	at carpet.script.utils.GlocalFlag.getWhileDisabled(GlocalFlag.java:28) ~[main/:?]
	at carpet.script.CarpetExpression.scriptRunCommand(CarpetExpression.java:111) ~[main/:?]
	at carpet.commands.ScriptCommand.lambda$compute$69(ScriptCommand.java:508) ~[main/:?]
	at carpet.commands.ScriptCommand.handleCall(ScriptCommand.java:440) ~[main/:?]
	at carpet.commands.ScriptCommand.compute(ScriptCommand.java:506) ~[main/:?]
	at carpet.commands.ScriptCommand.lambda$register$17(ScriptCommand.java:145) ~[main/:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:279) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:1347) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.method_44356(ServerGamePacketListenerImpl.java:1327) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.method_5386(BlockableEventLoop.java:67) ~[minecraft-project-@-merged-named.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:787) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:166) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:769) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:763) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:115) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:747) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zbf000$modifiedRunLoop(MinecraftServer.java:2917) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:655) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:264) ~[minecraft-project-@-merged-named.jar:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

**Comment by vlad2305m** [comment]
The problem is that, instead of just sending the shape to the client, you initialize the shape on the server first. Of course, not all rendering configurations are available on a standalone server ;)
Just replacing the enum values in question with their ordinal solves the issue.
```
@Environment(EnvType.CLIENT)
    public static enum Mode {
        LINES(4, 2, 2, false),
        LINE_STRIP(5, 2, 1, true),
        DEBUG_LINES(1, 2, 2, false),
        DEBUG_LINE_STRIP(3, 2, 1, true),
        TRIANGLES(4, 3, 3, false),
        TRIANGLE_STRIP(5, 3, 1, true),
        TRIANGLE_FAN(6, 3, 1, true),
        QUADS(4, 4, 4, false);
...
```

**Comment by vlad2305m** [comment]
Diffs:
github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/script/utils/ShapeDispatcher.java#L25
```
- import com.mojang.blaze3d.vertex.VertexFormat;
- import com.mojang.blaze3d.vertex.VertexFormat.Mode;
```
github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/script/utils/ShapeDispatcher.java#L766
`- .hasCode()`
Then
`TRIANGLES`->4; `TRIANGLE_FAN`->6; `TRIANGLE_STRIP`->5
github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/script/utils/ShapeDispatcher.java#L889
`Mode`->`int`
Then
`VertexFormat.Mode.TRIANGLE_FAN`->6; `VertexFormat.Mode.TRIANGLE_STRIP`->5; `VertexFormat.Mode.TRIANGLES`->4
 

github.com/gnembon/fabric-carpet/blob/master/src/main/java/carpet/script/utils/ShapesRenderer.java#L566
`shape.mode`->`VertexFormat.Mode.values()[shape.mode]`
Then replace `Mode.X` by integer values

**Comment by vlad2305m** [comment]
Yes I use Git instead of GitHub

**Comment by vlad2305m** [comment]
#1642

**Comment by altrisi** [comment]
I'm surprised it doesn't crash the server if it's loading a client only class.

**Comment by gnembon** [comment]
probably due to very broad catch around scarpet executions.

I think it warrants cherrypicking to 1.19.3

**Comment by altrisi** [comment]
Then I think we should also backport #1635 and if it's based on the `1.19.3` branch it needs d9a4a62f7cdc012888ebe8a0430c01f8393effae as there's currently an NPE in there.
