### ISSUE TITLE
Server is Requiring Carpet on Client Side?

### ISSUE THREAD

**Issue by PlatFormPlayZ** [gnembon/fabric-carpet#1767]
As I've always understood it, carpet was not needed client side in order to work. has this changed or did I setup the 1.20.1 fabric server wrong? Please help!
![image](https://github.com/gnembon/fabric-carpet/assets/68037788/4c6debdf-ea5e-4166-b46d-1cd54dac451e)

**Comment by James103** [comment]
Can you please post the client logs from attempting to join such a server, as mentioned in the disconnection screen?

**Comment by PlatFormPlayZ** [comment]
Due to vmware making it not easy to copy and paste in and out of the VM this was the quickest way I could grab the log...
![image](https://github.com/gnembon/fabric-carpet/assets/68037788/a08a0012-c280-43ce-a3d7-2978870c3b72)

**Comment by James103** [comment]
The attached screenshot appears to contain logs from the server. Do you also have the logs from the client? If so, can you please post them here?

**Comment by PlatFormPlayZ** [comment]
`[18:36:33] [Render thread/INFO]: Connecting to platformplayz.serveminecraft.net, 25565
[18:36:35] [Render thread/INFO]: Sending secret request to the server
[18:36:35] [Render thread/INFO]: Using 3 total BufferBuilder caches
[18:36:35] [Render thread/ERROR]: Received unknown remote registry entries from server
[18:36:35] [Render thread/ERROR]: Registry entry (carpet:crafting_table) is missing from local registry (minecraft:block_entity_type)
[18:36:35] [Render thread/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

carpet

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.checkRemoteRemap(RegistrySyncManager.java:388) ~[fabric-registry-sync-v0-2.2.6+b3afc78b77-2a2b63c9f8cdfd43.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:284) ~[fabric-registry-sync-v0-2.2.6+b3afc78b77-2a2b63c9f8cdfd43.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:118) ~[fabric-registry-sync-v0-2.2.6+b3afc78b77-2a2b63c9f8cdfd43.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
[18:36:35] [Render thread/INFO]: Clearing audio channels
[18:36:42] [Render thread/INFO]: Connecting to platformplayz.serveminecraft.net, 25565
[18:36:43] [Render thread/INFO]: Sending secret request to the server
[18:36:43] [Render thread/INFO]: Using 3 total BufferBuilder caches
[18:36:43] [Render thread/ERROR]: Received unknown remote registry entries from server
[18:36:43] [Render thread/ERROR]: Registry entry (carpet:crafting_table) is missing from local registry (minecraft:block_entity_type)
[18:36:43] [Render thread/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received a registry entry that is unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

carpet

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.checkRemoteRemap(RegistrySyncManager.java:388) ~[fabric-registry-sync-v0-2.2.6+b3afc78b77-2a2b63c9f8cdfd43.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:284) ~[fabric-registry-sync-v0-2.2.6+b3afc78b77-2a2b63c9f8cdfd43.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:118) ~[fabric-registry-sync-v0-2.2.6+b3afc78b77-2a2b63c9f8cdfd43.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:198) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
[18:36:43] [Render thread/INFO]: Clearing audio channels`

**Comment by James103** [comment]
> `[18:36:43] [Render thread/ERROR]: Registry entry (carpet:crafting_table) is missing from local registry (minecraft:block_entity_type)`

You are missing the `carpet-autoCraftingTable` mod, which adds the `carpet:crafting_table` block.
You will need to remove the mod from the server or install it on the client to join the server.

**Comment by PlatFormPlayZ** [comment]
weird... i didnt need it on my 1.19 server and when I just attempted to join my server with a fully vanilla client, it worked perfectly fine

**Comment by James103** [comment]
Do you have the full mod list for both the client and the server? If so, can you please post them here?

**Comment by PlatFormPlayZ** [comment]
Here are the server mods....
![image](https://github.com/gnembon/fabric-carpet/assets/68037788/c069f51a-6836-4323-a696-6feacd80c68e)
and the client side...
![image](https://github.com/gnembon/fabric-carpet/assets/68037788/bb614d90-5cc9-4e8a-851f-a1d0b30ece62)

**Comment by PlatFormPlayZ** [comment]
On the client side, adding the carpet mod and the carpet auto crafting table mod to the modlist produces an incompatibility between them and optifine and optifabric so upon disabling those two I am able to launch the game and join the server but I would prefer not to have to have the carpet mod locally in order to be able to use optifine and optifabric.

**Comment by PlatFormPlayZ** [comment]
I am going to add in my client mods one by one until I figure out what the issue is here cause using a fabric client with no mods in the mods folder is able to join the server so ill update this message when I figure it out...

**Comment by PlatFormPlayZ** [comment]
I tried v0.86 of the fabric api since the change log said something about a dynamic registry so I was hoping that would mean it could handle the auto crafting table but the problem I had with that version of the fabric API was that it was also incompatible with optifabric causing all text to become a rectangle kinda like so [] ... It was fruitless however.
![image](https://github.com/gnembon/fabric-carpet/assets/68037788/965e1574-e0bf-451c-aa86-00bb6dc1ecc1)

**Comment by PlatFormPlayZ** [comment]
This is actually an issue on [carpet-autoCraftingTable](https://github.com/gnembon/carpet-autoCraftingTable) under [Issue  #67 - Will be incompatible with clients without the mod and with Fabric API on 1.20+ or exactly 0.79.0](https://github.com/gnembon/carpet-autoCraftingTable/issues/67).
All this is due to a change on fabric API end where they patched a bug that was allowing it to be server side only but now its not and carpet and carpet auto crafter needs to be installed client side meaning officially carpet auto crafter is incompatible with optifine and optifabric.

**Comment by PlatFormPlayZ** [comment]
This is actually an issue on [carpet-autoCraftingTable](https://github.com/gnembon/carpet-autoCraftingTable) under [Issue  #67 - Will be incompatible with clients without the mod and with Fabric API on 1.20+ or exactly 0.79.0](https://github.com/gnembon/carpet-autoCraftingTable/issues/67). All this is due to a change on fabric API end where they patched a bug that was allowing it to be server side only but now its not and carpet and carpet auto crafter needs to be installed client side meaning officially carpet auto crafter is incompatible with optifine and optifabric.
