### ISSUE TITLE
After downloading breaking blocks doesn't drop their items

### ISSUE THREAD

**Issue by DezzNytes** [gnembon/fabric-carpet#1853]
Exactly what the title says. Don't really know how to resolve this issue. Sorry if resolved before, couldn't find a solution

**Comment by altrisi** [comment]
Cannot reproduce here with only Carpet.
Make sure the gamerule `doTileDrops` is set to true, given that disables drops.

If it still doesn't work, does it happen with just Carpet? In what version?
If not, can you try to find what mod it's conflicting with? Or at least send a log/mod list?

**Comment by Gilithrimm** [comment]
Same issue here, it appeared after adding [Random Assistant](https://github.com/Bawnorton/RandoAssistant).
Each time I broke any block an error occurred:
```
[20:26:40] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2805@4c3063e, suppressing error
java.lang.NullPointerException: Cannot read field "handler" because the return value of "carpet.script.CarpetEventServer$Event.getEvent(String, carpet.script.CarpetScriptServer)" is null
	at carpet.script.ScriptCommand.lambda$register$48(ScriptCommand.java:342) ~[fabric-carpet-1.20-1.4.112+v230608.jar:?]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.1.8.jar:?]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:599) ~[brigadier-1.1.8.jar:?]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:581) ~[brigadier-1.1.8.jar:?]
	at net.minecraft.class_3244.method_12059(class_3244.java:537) ~[client-intermediary.jar:?]
	at net.minecraft.class_2805.method_12147(class_2805.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_2805.method_11054(class_2805.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:743) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zcf000$carpet$modifiedRunLoop(MinecraftServer.java:5951) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
Also here's the log file in case it's needed
[carpet breaking.log](https://github.com/gnembon/fabric-carpet/files/15053073/carpet.breaking.log)
