### ISSUE TITLE
/Player Broken in 1.20.4

### ISSUE THREAD

**Issue by CyberSpace-77** [gnembon/fabric-carpet#1888]
After typing /player (Player Name) nothing happens. No player spawned

**Comment by Daniel99j2** [comment]
Works for me, but please send your log file.
Do you have other mods? If so, what ones?

**Comment by CyberSpace-77** [comment]
[2024-03-20-5.log](https://github.com/gnembon/fabric-carpet/files/14692208/2024-03-20-5.log)

The Mods I Use are
AppleSkin
Axiom
Better Command Block UI
Carpet + Carpet Fixes
Cloth Config
Comforts
Concurrent Chunk Management
Continuity
Debugify
Entity Culling
Fabric API
Fabric Language Kotlin
Ferrite Core
Free Cam
Immediately Fast
Indium
Iris
Item Scroller
LambDynamicLights
LazyDFU
Litematica
Lithium
MaliLIb
MiniHUD
MixinTrace
Mod Menu
Modern Fix
More Culling
Mouse Tweaks
No Chat Reports
Reese's Sodium Options
Shulkerbox Tool Tip
Sodium
Sodium Extra
Starlight
Thread Tweak
Tweakeroo
Very Many Players
World Edit
Xaero's Mini + World Map
Yet another Config Lib
Zoomify

**Comment by Oururis** [comment]
same i

**Comment by Daniel99j2** [comment]
Can you try removing c2me…
I have the mod and it works with fake players, so might be something else

**Comment by Daniel99j2** [comment]
More specifically
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_3898.handler$zfd000$c2me-fixes-general-threading-issues$preventAsyncEntityLoad(class_3898.java:10407)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_3898.method_18701(class_3898.java)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_3215.method_18755(class_3215.java:481)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1585)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1563)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_5579.method_31847(class_5579.java:216)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_5579.method_31820(class_5579.java:186)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_5579.method_31818(class_5579.java:167)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_3218.method_18771(class_3218.java:924)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_3218.method_18213(class_3218.java:910)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_3324.md5bd366$vmp$lambda$redirectRequestTeleport$0$3(class_3324.java:8048)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_3324.redirect$ffb000$vmp$redirectRequestTeleport(class_3324.java:8060)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at net.minecraft.class_3324.method_14570(class_3324.java:214)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at carpet.patches.EntityPlayerMPFake.lambda$createFake$2(EntityPlayerMPFake.java:76)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:653)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
[19:54:57] [Worker-Main-8/INFO]: [STDERR]: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

**Comment by Oururis** [comment]
> Can you try removing c2me… I have the mod and it works with fake players, so might be something else

yep, I've tried it because I saw it in another issue

**Comment by Oururis** [comment]
> Can you try removing c2me… I have the mod and it works with fake players, so might be something else

I forgot to mention, it was C2em that caused a conflict with fakeplayer . everything went back to normal after I uninstalled C2em.

**Comment by CyberSpace-77** [comment]
After I do the command The bot is in the tab list but It is completely invisible and hit-boxes don't show where they are either

**Comment by Oururis** [comment]
> After I do the command The bot is in the tab list but It is completely invisible and hit-boxes don't show where they are either

yes, I had the same issue as you, and it got resolved after I uninstalled C2ME

you can try to find out if there's a mod causing fakeplayer to malfunction

The easiest way is to check the crash report, but this might not work well since the game isn't crashing

If you're using a third party launcher , you could try installing the same version of Minecraft in a new directory . Then, gradually add 5~10 mods at a time and eliminate which mod is causing this error to occur  ,
this method is very effective . I have a total of 181 mods, and I was able to identify another issue in less than an hour using this approach. This one should be even quicker. Anyway, good luck to you

**Comment by CyberSpace-77** [comment]
Found the Issue The Mod Very many Players Broke the Command
