### ISSUE TITLE
[bug]I use minecraft 1.20.4 with carpet 1.4.128 can't join my MInecraft server

### ISSUE THREAD

**Issue by laoliuhhh** [gnembon/fabric-carpet#1930]
It's on line 1924.  [log](https://mclo.gs/YyCWexJ#L4924)

The server uses Velocity's default connection to a Paper server, and when I switch to the Fabric server, I get the following error message: "Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(16397) + length(1) exceeds writerIndex(16397): PooledUnsafeDirectByteBuf(ridx: 16397, widx: 16397, cap: 16397)".

This is a list of server mods：
'[地形]ctov-3.4.2.jar.old'                                            fabric-language-kotlin-1.10.19+kotlin.1.9.23.jar
'[地形]tectonic-fabric-1.20-v2.2.jar1'                                ForceAccessServer-forge-fabric-1.0.3.jar
'[地形]Terralith_1.20.4_v2.4.11_FABRIC.jar1'                          geckolib-fabric-1.20.4-4.4.4.jar
'[地形]Towns-and-Towers-1.12.0.jar.old'                               Jade-1.20.4-fabric-13.3.1.jar
'[辅助](必掉凋零头)alwaysawitherskull-1.20.4-3.2.jar'                 ledger-1.2.10.jar
'[辅助](船可上岸)moveboats-1.20.4-3.2.jar'                            ledger-databases-1.1.1.jar
'[辅助](更好的地狱门)cryingportals-1.20.4-2.7.jar'                   '[lib]collective-1.20.4-7.32.jar.old'
'[辅助](共享原理图)syncmatica-1.20.2-0.3.11.jar'                     '[lib]cristellib-1.2.4-fabric.jar'
'[辅助](监工)Dynmap-3.7-beta-4-fabric-1.20.4.jar'                    '[lib]ctLibMod-0.0.15.jar'
'[辅助](快速整理)quicksort-0.8.0+1.20.4.jar'                         '[lib]fabric-api-0.96.3+1.20.4.jar.old'
'[辅助](旅商出售玩家丢失物品)wanderingcollector-1.2.1+mc1.20.4.jar'  '[lib]fabric-language-kotlin-1.10.18+kotlin.1.9.22.jar.old'
'[辅助](末地传送门配方)endportalrecipe-1.20.4-5.2.jar'               '[lib]ForgeConfigAPIPort-v20.4.3-1.20.4-Fabric.jar'
'[辅助](潜行右键隐藏展示框)invisibleframes-1.1.0+1.20.jar'           '[lib]geckolib-fabric-1.20.4-4.4.2.jar.old'
'[辅助](史莱姆区块查找)slimyfloor-1.20-1.2.8.jar'                    '[lib]magiclib-all-0.7.398+fe2125a-stable.jar'
'[辅助](头颅菜单)headindex-1.1.5.jar'                                 PacketFixer-fabric-1.20.4-1.2.4.jar
'[辅助](minihub支持)servux-fabric-1.20.2-0.1.0.jar'                   quickshulker-1.4.0-1.20.jar
'[占位符互通]PAPIProxyBridge-1.5.jar'                                 remote-inventory-1.20.2-1.3.jar
'[占位符]placeholder-api-2.3.0+1.20.3.jar'                           '[server](查熊)ledger-1.2.10.jar.old'
'[carpet]carpet-extra-1.20.3-1.4.128.jar'                            '[server](锂)lithium-fabric-mc1.20.4-0.12.1.jar'
'[carpet]carpet-org-addition-mc1.20.4-2402101556-1.23.0.jar.old'     '[server](内存优化)ferritecore-6.0.3-fabric.jar'
'[carpet]carpet-tis-addition-mc1.20.4-v1.56.1.jar1'                  '[server]krypton-0.2.6.jar'
'[carpet]fabric-carpet-1.20.3-1.4.128+v231205.jar'                   '[server]lazydfu-0.1.3.jar'
'[carpet]gugle-carpet-addition-2.7.0-1.20.4.jar'                     '[server]MCDRcommandFabric-1.20.4-v1.2.1.jar'
'carpet-org-addition-mc1.20.4-2404061618-1.26.2 (1).jar'              ServerReplay-1.0.7+mc1.20.4.jar.old
 carpet-org-addition-mc1.20.4-2404061618-1.26.2.jar                   ServerReplay-1.0.8+mc1.20.4.jar
'[carpet]PluslsCarpetAddition-1.20.4-0.3.190+9e97daa-beta.jar'       '[server]starlight-1.1.3+fabric.f5dcd1a.jar'
 chesttracker-2.3.3+1.20.4.jar                                       '[server](velocity支持)FabricProxy-Lite-2.7.0.jar'
 Chunky-1.3.138.jar                                                   spark-1.10.58-fabric.jar
 collective-1.20.4-7.40.jar                                           t_and_t-1.12.1.1.jar
 ctov-fabric-3.4.3.jar                                                voicechat-fabric-1.20.4-2.5.16.jar.bak
 fabric-api-0.96.11+1.20.4.jar                                        XaerosWorldMap_1.38.1_Fabric_1.20.4.jar

I guess the problem is usually some stupid mod that miswrites ByteBuf.

**Comment by laoliuhhh** [comment]
English is not my native language and I may struggle to articulate myself effectively.

**Comment by sakura-ryoko** [comment]
`<html><body>

at dzwdz.chat_heads.ChatHeads$PlayerInfoCache.createNamesByFirstCharacterMap(ChatHeads.java:286) ~[%5B����ͷ��%5D%20chat_heads-0.12.0-fabric-1.20.3.jar:?]
--
 

<span class="level level-error multiline">	at net.minecraft.class_7594.handler$bom000$chat_heads$chatheads$handleAddedSystemMessage(class_7594.java:1045) ~[client-intermediary.jar:?]</span>
</body>
</html>`

**Comment by laoliuhhh** [comment]
no
Not the reason for this mod
