### ISSUE TITLE
When trying to spawn fake players the game crashes.

### ISSUE THREAD

**Issue by OmARRR-LANG** [gnembon/fabric-carpet#1952]
for some reason the game just crashes after I try to spawn a player I run at 1.21 and here is the crash log:

Picked up _JAVA_OPTIONS: 
[08:34:13] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[08:34:14] [main/INFO]: Loading 5 mods:
	- carpet 1.4.147+v240613
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- java 21
	- minecraft 1.21
[08:34:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/OmarM/AppData/Roaming/.tlauncher/legacy/Minecraft/game/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[08:34:14] [main/INFO]: Compatibility level set to JAVA_17
[08:34:16] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[08:34:16] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 525 milliseconds
[08:34:23] [Render thread/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=https://authserver.ely.by/services]
[08:34:23] [Render thread/INFO]: CAFixer is not available: java.lang.NoClassDefFoundError: com/turikhay/caf/util/Logger
[08:34:23] [Render thread/INFO]: Setting user: OmarCrab
[08:34:23] [Render thread/ERROR]: Error parsing option value 15.0 for option Brightness: Failed to parse either. First: Value 15.0 outside of range [0.0:1.0]; Second: Not a boolean: 15.0
[08:34:23] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[08:34:24] [Render thread/WARN]: Removed resource pack fabric from options because it doesn't seem to exist anymore
[08:34:25] [Render thread/INFO]: Reloading ResourceManager: vanilla
[08:34:26] [Worker-Main-2/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading
[08:34:26] [Worker-Main-7/INFO]: Found unifont_jp_patch-15.1.05.hex, loading
[08:34:27] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[08:34:27] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[08:34:27] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Speakers (Realtek(R) Audio)
[08:34:27] [Render thread/INFO]: Sound engine started
[08:34:27] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[08:34:27] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[08:34:27] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[08:34:27] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[08:34:27] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[08:34:27] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[08:34:27] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[08:34:27] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[08:34:27] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[08:34:28] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[08:34:28] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[08:34:28] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[08:34:28] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[08:34:28] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[08:34:28] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[08:34:31] [Worker-Main-4/ERROR]: Exception reading C:\Users\OmarM\AppData\Roaming\.tlauncher\legacy\Minecraft\game\home\Fabric 1.21\saves\New World (19)\level.dat
java.util.zip.ZipException: invalid distance too far back
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:181) ~[?:?]
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:128) ~[?:?]
	at java.base/java.util.zip.InflaterInputStream.skip(InflaterInputStream.java:228) ~[?:?]
	at net.minecraft.class_6826.skip(class_6826.java:68) ~[client-intermediary.jar:?]
	at java.base/java.io.DataInputStream.skipBytes(DataInputStream.java:233) ~[?:?]
	at net.minecraft.class_2519.method_39875(class_2519.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_39851(class_2487.java:160) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_39851(class_2487.java:161) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_53888(class_2487.java:124) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_39852(class_2487.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_53888(class_2487.java:129) ~[client-intermediary.jar:?]
	at net.minecraft.class_2487$1.method_39852(class_2487.java:88) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_39855(class_2507.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_40058(class_2507.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_2507.method_40057(class_2507.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_32.method_40035(class_32.java:312) ~[client-intermediary.jar:?]
	at net.minecraft.class_32.method_54527(class_32.java:248) ~[client-intermediary.jar:?]
	at net.minecraft.class_32.method_43418(class_32.java:178) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?]
[08:34:33] [Render thread/INFO]: Loaded 1290 recipes
[08:34:33] [Render thread/INFO]: Loaded 1399 advancements
[08:34:33] [Server thread/INFO]: Starting integrated minecraft server version 1.21
[08:34:33] [Server thread/INFO]: Generating keypair
[08:34:33] [Server thread/INFO]: [CM] Loaded 2 settings from carpet.conf
[08:34:35] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[08:34:35] [Render thread/INFO]: Preparing spawn area: 0%
[08:34:35] [Render thread/INFO]: Preparing spawn area: 89%
[08:34:35] [Render thread/INFO]: Time elapsed: 684 ms
[08:34:36] [Server thread/INFO]: Changing view distance to 19, from 10
[08:34:36] [Server thread/INFO]: Changing simulation distance to 32, from 0
[08:34:37] [Server thread/INFO]: OmarCrab[local:E:9a193181] logged in with entity id 17 at (2590.6806341371307, 66.0, -216.3041601798627)
[08:34:37] [Server thread/INFO]: OmarCrab joined the game
[08:34:37] [Render thread/INFO]: Loaded 567 advancements
[08:34:38] [Render thread/WARN]: Received passengers for unknown entity
[08:34:38] [Render thread/WARN]: Received passengers for unknown entity
[08:34:38] [Render thread/WARN]: Received passengers for unknown entity
[08:34:38] [Render thread/WARN]: Received passengers for unknown entity
[08:34:38] [Render thread/WARN]: Received passengers for unknown entity
[08:34:42] [Server thread/INFO]: Saving and pausing game...
[08:34:42] [Server thread/INFO]: Saving chunks for level 'ServerLevel[ITS ME]'/minecraft:overworld
[08:34:42] [Server thread/INFO]: Saving chunks for level 'ServerLevel[ITS ME]'/minecraft:the_nether
[08:34:42] [Server thread/INFO]: Saving chunks for level 'ServerLevel[ITS ME]'/minecraft:the_end
[08:34:43] [Render thread/INFO]: Using default channel type
[08:34:43] [Render thread/INFO]: Started serving on 53079
[08:34:43] [Render thread/INFO]: [System] [CHAT] Local game hosted on port [53079]
[08:35:13] [Render thread/WARN]: Received passengers for unknown entity
[08:35:43] [Server thread/WARN]: Can't keep up! Is the server overloaded? Running 2044ms or 40 ticks behind
[08:35:49] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'void com.mojang.authlib.GameProfileRepository.findProfilesByNames(java.lang.String[], com.mojang.authlib.ProfileLookupCallback)'
	at net.minecraft.class_3312.method_14509(class_3312.java:95) ~[client-intermediary.jar:?]
	at net.minecraft.class_3312.method_14515(class_3312.java:150) ~[client-intermediary.jar:?]
	at carpet.commands.PlayerCommand.cantSpawn(PlayerCommand.java:198) ~[fabric-carpet-1.21-1.4.147+v240613.jar:?]
	at carpet.commands.PlayerCommand.spawn(PlayerCommand.java:250) ~[fabric-carpet-1.21-1.4.147+v240613.jar:?]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.class_8865.method_54416(class_8865.java:29) ~[client-intermediary.jar:?]
	at net.minecraft.class_8865.execute(class_8865.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_8856.method_54405(class_8856.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_8847.method_54388(class_8847.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_8854.method_54390(class_8854.java:107) ~[client-intermediary.jar:?]
	at net.minecraft.class_2170.method_54313(class_2170.java:379) ~[client-intermediary.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:309) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_58590(class_3244.java:1319) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_44356(class_3244.java:1307) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:121) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[client-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[08:35:49] [Server thread/ERROR]: This crash report has been saved to: C:\Users\OmarM\AppData\Roaming\.tlauncher\legacy\Minecraft\game\home\Fabric 1.21\crash-reports\crash-2024-07-17_08.35.49-server.txt
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2024-07-17 08:35:49
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'void com.mojang.authlib.GameProfileRepository.findProfilesByNames(java.lang.String[], com.mojang.authlib.ProfileLookupCallback)'
	at net.minecraft.class_3312.method_14509(class_3312.java:95)
	at net.minecraft.class_3312.method_14515(class_3312.java:150)
	at carpet.commands.PlayerCommand.cantSpawn(PlayerCommand.java:198)
	at carpet.commands.PlayerCommand.spawn(PlayerCommand.java:250)
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73)
	at net.minecraft.class_8865.method_54416(class_8865.java:29)
	at net.minecraft.class_8865.execute(class_8865.java:13)
	at net.minecraft.class_8856.method_54405(class_8856.java:8)
	at net.minecraft.class_8847.method_54388(class_8847.java:8)
	at net.minecraft.class_8854.method_54390(class_8854.java:107)
	at net.minecraft.class_2170.method_54313(class_2170.java:379)
	at net.minecraft.class_2170.method_9249(class_2170.java:309)
	at net.minecraft.class_3244.method_58590(class_3244.java:1319)
	at net.minecraft.class_3244.method_44356(class_3244.java:1307)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:162)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:864)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:173)
	at net.minecraft.class_1255.method_16075(class_1255.java:136)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:846)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:840)
	at net.minecraft.class_1255.method_5383(class_1255.java:121)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:814)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:702)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281)
	at java.base/java.lang.Thread.run(Thread.java:1583)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.21
	Minecraft Version ID: 1.21
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 7585398784 bytes (7234 MiB) / 10427039744 bytes (9944 MiB) up to 13958643712 bytes (13312 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 2600X Six-Core Processor           
	Identifier: AuthenticAMD Family 23 Model 8 Stepping 2
	Microarchitecture: Zen+
	Frequency (GHz): 3.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660 Ti
	Graphics card #0 vendor: NVIDIA
	Graphics card #0 VRAM (MiB): 6144.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.15.5599
	Memory slot #0 capacity (MiB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MiB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MiB): 28081.88
	Virtual memory used (MiB): 19758.64
	Swap memory total (MiB): 11776.00
	Swap memory used (MiB): 401.42
	Space in storage for jna.tmpdir (MiB): available: 778418.00, total: 976654.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 778418.00, total: 976654.00
	Space in storage for io.netty.native.workdir (MiB): available: 778418.00, total: 976654.00
	Space in storage for java.io.tmpdir (MiB): available: 778418.00, total: 976654.00
	Space in storage for workdir (MiB): available: 778418.00, total: 976654.00
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseZGC -XX:-ZUncommit -XX:ZCollectionInterval=5 -XX:ZAllocationSpikeTolerance=2.0 -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -Xms5105M -Xmx13312M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss2M
	Server Running: true
	Player Count: 1 / 8; [class_3222['OmarCrab'/17, l='ServerLevel[ITS ME]', x=-24.23, y=68.00, z=21.45]]
	Active Data Packs: vanilla
	Available Data Packs: bundle, trade_rebalance, vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	World Seed: 0
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: Fabric 1.21
[08:35:49] [Server thread/INFO]: Stopping server
[08:35:49] [Server thread/INFO]: Saving players
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\OmarM\AppData\Roaming\.tlauncher\legacy\Minecraft\game\home\Fabric 1.21\crash-reports\crash-2024-07-17_08.35.49-server.txt

also I suspect it may be from the client.

**Comment by abwmocc** [comment]
I'm having the same issue as you,my server version is 1.20.4.When I try to spawn a new fake player,there is a chance that the server will crash.The error message on the server is that it takes too long to execute 1tick like yours.This question has been bothering me and I don't know how to settle.I installed the carpet extend "carpet-tis-addition" to make the fake player have the bot_ prefix.I also installed "gugle-carpet-addition" to open fake players' inventory.Are you in the same situation as me?Have you solved this problem?Thanks.
