### ISSUE TITLE
1.21.1 incompatible with Lithium mod mixin

### ISSUE THREAD

**Issue by Fungus-00** [gnembon/fabric-carpet#1973]
# Version
- Fabric loader: 0.15.11
- Fabric api: 0.102.1+1.21.1
- Carpet: 1.4.147+v240809
- Lithium: 0.13.0+1.21.1

# Logs
```
[Server] [14:36:30] [main/WARN]: @Redirect conflict. Skipping carpet.mixins.json:Explosion_scarpetEventMixin from mod carpet->@Redirect::onExplosion(Lnet/minecraft/class_243;Lnet/minecraft/class_1297;)F with priority 990, already redirected by lithium.mixins.json:world.explosions.cache_exposure.ExplosionMixin from mod lithium->@Redirect::returnCachedExposure(Lnet/minecraft/class_243;Lnet/minecraft/class_1297;)F with priority 1000
[Server] [14:36:30] [main/ERROR]: Minecraft has crashed!
[Server] net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
[Server] 	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:472) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.21.1-loader.0.15.11-launcher.1.0.1.jar:1.0.1]
[Server] Caused by: java.lang.ExceptionInInitializerError
[Server] 	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2966.method_12851(class_2966.java:52) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
[Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
[Server] 	... 4 more
[Server] Caused by: net.minecraft.class_148: Lithium Class Analysis
[Server] 	at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.hasMethodOverride(ReflectionUtil.java:46) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.isBlockStateEntityTouchable(ReflectionUtil.java:64) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at me.jellysquid.mods.lithium.common.block.BlockStateFlags$6.test(BlockStateFlags.java:116) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at me.jellysquid.mods.lithium.common.block.BlockStateFlags$6.test(BlockStateFlags.java:113) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at net.minecraft.class_4970$class_4971.initFlags(class_4970.java:2392) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_4970$class_4971.handler$bgk002$lithium$init(class_4970.java:2381) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:872) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2246.<clinit>(class_2246.java:1259) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2966.method_12851(class_2966.java:52) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
[Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
[Server] 	... 4 more
[Server] Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_1927 failed
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
[Server] 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
[Server] 	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:?]
[Server] 	at java.base/java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:?]
[Server] 	at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.hasMethodOverride(ReflectionUtil.java:23) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.isBlockStateEntityTouchable(ReflectionUtil.java:64) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at me.jellysquid.mods.lithium.common.block.BlockStateFlags$6.test(BlockStateFlags.java:116) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at me.jellysquid.mods.lithium.common.block.BlockStateFlags$6.test(BlockStateFlags.java:113) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at net.minecraft.class_4970$class_4971.initFlags(class_4970.java:2392) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_4970$class_4971.handler$bgk002$lithium$init(class_4970.java:2381) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:872) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2246.<clinit>(class_2246.java:1259) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2966.method_12851(class_2966.java:52) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
[Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
[Server] 	... 4 more
[Server] Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[Server] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
[Server] 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
[Server] 	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:?]
[Server] 	at java.base/java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:?]
[Server] 	at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.hasMethodOverride(ReflectionUtil.java:23) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.isBlockStateEntityTouchable(ReflectionUtil.java:64) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at me.jellysquid.mods.lithium.common.block.BlockStateFlags$6.test(BlockStateFlags.java:116) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at me.jellysquid.mods.lithium.common.block.BlockStateFlags$6.test(BlockStateFlags.java:113) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at net.minecraft.class_4970$class_4971.initFlags(class_4970.java:2392) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_4970$class_4971.handler$bgk002$lithium$init(class_4970.java:2381) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:872) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2246.<clinit>(class_2246.java:1259) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2966.method_12851(class_2966.java:52) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
[Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
[Server] 	... 4 more
[Server] Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector onExplosion(Lnet/minecraft/class_243;Lnet/minecraft/class_1297;)F in carpet.mixins.json:Explosion_scarpetEventMixin from mod carpet failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json
[Server] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
[Server] 	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
[Server] 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
[Server] 	at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:?]
[Server] 	at java.base/java.lang.Class.getDeclaredMethod(Unknown Source) ~[?:?]
[Server] 	at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.hasMethodOverride(ReflectionUtil.java:23) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at me.jellysquid.mods.lithium.common.reflection.ReflectionUtil.isBlockStateEntityTouchable(ReflectionUtil.java:64) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at me.jellysquid.mods.lithium.common.block.BlockStateFlags$6.test(BlockStateFlags.java:116) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at me.jellysquid.mods.lithium.common.block.BlockStateFlags$6.test(BlockStateFlags.java:113) ~[lithium-fabric-mc1.21.1-0.13.0.jar:?]
[Server] 	at net.minecraft.class_4970$class_4971.initFlags(class_4970.java:2392) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_4970$class_4971.handler$bgk002$lithium$init(class_4970.java:2381) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:872) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2246.<clinit>(class_2246.java:1259) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2358.method_10199(class_2358.java:336) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.class_2966.method_12851(class_2966.java:52) ~[server-intermediary.jar:?]
[Server] 	at net.minecraft.server.Main.main(Main.java:108) ~[server-intermediary.jar:?]
[Server] 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
[Server] 	... 4 more
```

**Comment by Reinitialized** [comment]
This appears to apply with 1.21.x as a whole so far, as 1.21 also crashes with Lithium and Carpet combined. Exact same error as above, can post a log if desired.

**Comment by schrummy14** [comment]
Error occurs in an explosion optimization portion of lithium. You can add a flag in your lithium config to get things to work.
https://github.com/CaffeineMC/lithium-fabric/issues/543

**Comment by ArduFish123** [comment]
Can confirm

**Comment by JoelHer** [comment]
Same issue here.

**Comment by SBananajr** [comment]
It stops crashing if you add the line "mixin.world.explosions.cache_exposure=false" to the lithium properties file (which is in the config folder).

**Comment by bluesteamhost** [comment]
> Error occurs in an explosion optimization portion of lithium. You can add a flag in your lithium config to get things to work. [CaffeineMC/lithium-fabric#543](https://github.com/CaffeineMC/lithium-fabric/issues/543)

You sir are awesome!

> It stops crashing if you add the line "mixin.world.explosions.cache_exposure=false" to the lithium properties file (which is in the config folder).

Can confirm that this worked :-D  thanks for the tip. You're a legend.

**Comment by purple-emily** [comment]
I can confirm that the crashes occur in the latest releases of everything and is fixed with the above Lithium change

**Comment by Fallensakura715** [comment]
> > Error occurs in an explosion optimization portion of lithium. You can add a flag in your lithium config to get things to work. [CaffeineMC/lithium-fabric#543](https://github.com/CaffeineMC/lithium-fabric/issues/543)
> 
> You sir are awesome!
> 
> > It stops crashing if you add the line "mixin.world.explosions.cache_exposure=false" to the lithium properties file (which is in the config folder).
> 
> Can confirm that this worked :-D thanks for the tip. You're a legend.

awesome!
