### ISSUE TITLE
[Bug] Scoreboard bug (I can't explain beyond that)

### ISSUE THREAD

**Issue by Ghoulboy78** [gnembon/fabric-carpet#249]
here is the crash report. I hope you can make sense of it, man!
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 24/04/20 10:31
Description: Exception in server tick loop

java.lang.IllegalArgumentException: An objective with the name 'Speed' already exists!
	at net.minecraft.class_269.method_1168(class_269.java:54)
	at net.minecraft.class_273.method_17947(class_273.java:139)
	at net.minecraft.class_273$$Lambda$3614/4947657.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_273.method_1220(class_273.java:131)
	at net.minecraft.class_273.method_77(class_273.java:42)
	at net.minecraft.class_273.method_1218(class_273.java:31)
	at net.minecraft.server.MinecraftServer.method_17976(MinecraftServer.java:276)
	at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:400)
	at net.minecraft.class_1132.method_3735(class_1132.java:84)
	at net.minecraft.class_1132.method_3823(class_1132.java:106)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:628)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 736832872 bytes (702 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Player Count: 0 / 8; []
	Data Packs: vanilla
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

When I commented out the line `//scoreboard_add('Speed');` in the .sc file it opened again, which is weird cos it didnt even have a __config defined!

**Comment by gnembon** [comment]
so what you are saying that adding an objective that already exists causes exception thrown, right?

**Comment by Ghoulboy78** [comment]
that my guess

**Comment by gnembon** [comment]
trying hard to break it - couldn't the way you did.

**Comment by Ghoulboy78** [comment]
basically u make a scoreboard, say caled 'score', in a scarpet app. after tunning the app, log out, then restart (idk about the restart, but that's how I came across this) and then you should notice your game crashes. I tried 3 times, then I commented out the line which added the scoreboard `//scoreboard_add('Speed')` and then it didn't crash

**Comment by Ghoulboy78** [comment]
If you can't reproduce, then maybe it's been accidently fixed.
