### ISSUE TITLE
Carpet mod incompatibility with OptiFabric and Optifine Pre-Releases 1.16.1

### ISSUE THREAD

**Issue by Scorpion34** [gnembon/fabric-carpet#389]
basically in the title the issue is with optifabric, optifabric recognizes the optifine file just fine but when it gets to carpet mod the game immediately crashes due to unknown modifications to the game so things like tick rate is undefinable and no xpcooldown among others and considering the lack of support with optifabric going forward the only solution is to hopefully get carpet to have it's code modified to work with optifine and optifabric at it's current state because currently optifine pre-release 8 has been released but I'm still stuck on pre-release 4 due to lack of support from optifabric and the game crashing from carpet mod so basically I'm left in a position of updating my optifine and lose carpet mod or stay on optifine pre-release 4 and deal with very annoying bugs and keep carpet mod for my survival world to optimize my farms and have afk players kind of at a stand-still was curious if there are any intentions to resolve this issue.

**Comment by Ghoulboy78** [comment]
Can you post crash report?

**Comment by gnembon** [comment]
I fixed that issue yesterday releasing ....build2 for 1.4.0
Does if happen with this jar?

**Comment by Scorpion34** [comment]
> Can you post crash report?

Well I could but gnembon fixed this with build2 but the crash report was basically Optifabric and Optifine were being recognized but carpet mod wasn't causing interference and the game crashes I'll show the crash report here though incase you were wondering
=================================================================================
[15:13:56] [main/INFO]: Loading for game Minecraft 1.16.1
[15:13:56] [main/INFO]: [FabricLoader] Loading 56 mods: fabric-renderer-api-v1@0.2.13+eae12eb802, fabric-keybindings-v0@0.2.0+3fa9f7c502, fabricloader@0.9.0+build.204, org_zeroturnaround_zt-zip@1.14, bbor@2.3-1.16.1, fabric-containers-v0@0.1.8+045df74f02, fabric-object-builder-api-v1@1.5.5+e00ecb5f02, fabric-dimensions-v1@1.0.0+a71b305302, fabric-api-base@0.1.3+12a8474c02, mm@2.0, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, fabric-textures-v0@1.0.4+eae12eb802, fabric-rendering-fluids-v1@0.1.8+b7084faa02, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, fabric-lifecycle-events-v1@1.1.0+013e49d202, fabric-renderer-registries-v1@2.0.1+5a0f9a6002, minihud@0.19.0-dev.20200701.005153, tabinventory@1.0.0-1.16, fabric-loot-tables-v1@1.0.0+386eb69e02, fabric@0.15.0+build.379-1.16.1, org_slf4j_slf4j-api@1.7.30, carpet@1.4.0, fabric-particles-v1@0.2.1+0a6f2a7002, fabric-networking-v0@0.1.10+e00ecb5f02, fabric-screen-handler-api-v1@1.0.1+f362c86e02, minecraft@1.16.1, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, modmenu@1.14.5+build.30, fabric-command-api-v1@1.0.8+5ce5339802, cloth-basic-math@0.5.1, fabric-tool-attribute-api-v1@1.1.4+5794386e02, fabric-renderer-indigo@0.3.3+013e49d202, fabric-biomes-v1@0.2.7+059ea86602, fabric-events-interaction-v0@0.3.3+7066030f02, org_slf4j_slf4j-simple@1.7.30, fabric-item-api-v1@1.0.0+16acbe5b02, fabric-crash-report-info-v1@0.1.2+b7f9825d02, fabric-rendering-v0@1.1.0+5341049002, fabric-rendering-v1@1.1.2+346247d702, fabric-key-binding-api-v1@1.0.0+e16a977402, cloth-config2@4.5.6, fabric-resource-loader-v0@0.2.6+f41e209802, autoconfig1u@3.2.0-unstable, malilib@0.10.0-dev.21+arne.1, fabric-content-registries-v0@0.1.9+059ea86602, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, worldedit@7.2.0-beta-02+d10d7d6, optifabric@1.1.0-beta2, fabric-registry-sync-v0@0.3.8+7dba2d6c02, fabric-commands-v0@0.2.0+52d3083602, fabric-mining-levels-v0@0.1.2+b764ce9902, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, fabric-models-v0@0.1.0+dfdb52d602, fabric-item-groups-v0@0.2.0+438f963602, shulkerboxtooltip@2.1.0+1.16.1, fabric-object-builders-v0@0.6.0+da175ad602
[15:13:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/E:/MultiMC/MultiMC/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
Optifabric is still using the traditional Early Riser initialisation
Found existing patched optifine jar, using that
org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method changeTickPhase(F)F in carpet.mixins.json:WorldRenderer_pausedShakeMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:302)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:413)
	at net.minecraft.client.main.Main.main(Main.java:135)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:194)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	... 10 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:302)
	at net.minecraft.class_128.method_559(class_128.java:101)
	at net.minecraft.class_128.<init>(class_128.java:54)
	at net.minecraft.class_128.method_24305(class_128.java:413)
	at net.minecraft.client.main.Main.main(Main.java:135)
	... 15 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method changeTickPhase(F)F in carpet.mixins.json:WorldRenderer_pausedShakeMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 26 more
Exiting with -1
Process exited with code -1.
===================================================================================
not entirely sure what parts of the code were necessary but that's the error I receive and you'll see all the mods I have I use multimc so hopefully this is the correct piece of code not a very savvy user of multimc but anyways this was the main problem which has since been fixed so thank you very much :)

**Comment by Ghoulboy78** [comment]
you can close now ig

**Comment by Scorpion34** [comment]
> you can close now ig

I was just about to comment my thanks to gnembon and then close

**Comment by Ghoulboy78** [comment]
ok, don't tell me just do it

**Comment by Scorpion34** [comment]
> I fixed that issue yesterday releasing ....build2 for 1.4.0
> Does if happen with this jar?

With the file from curseforge this one fabric-carpet-1.16-1.4.0+v200623.jar the issue is still apparent but with build2 this issue is resolved not exactly sure how you mean if it happens with the jar but I use multimc to store all my mods it does happen outside of multimc though but the issue has been fixed with build2 just tested this and it seems to be working fantastically so thank you for the quick response and your time :)
