### ISSUE TITLE
Server crashing with mocking true

### ISSUE THREAD

**Issue by Danielweber2007** [gnembon/fabric-carpet#39]
here is the crash message:
net.minecraft.class_148: Exception ticking world
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:828) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:343) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:763) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.handler$modifiedRunLoop$zzj000(MinecraftServer.java:2242) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:610) [intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
        at carpet.utils.SpawnReporter.registerSpawn(SpawnReporter.java:82) ~[fabric-carpet-v19_06_24_for_14_3_sunny.jar:?]
        at net.minecraft.class_1948.redirect$spawnEntity$zch000(class_1948.java:589) ~[intermediary-server.jar:?]
        at net.minecraft.class_1948.method_8663(class_1948.java:157) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215.redirect$spawnMultipleTimes$zcg000(class_3215.java:1108) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215.method_20801(class_3215.java:362) ~[intermediary-server.jar:?]
        at it.unimi.dsi.fastutil.longs.Long2ObjectLinkedOpenHashMap$1.forEach(Long2ObjectLinkedOpenHashMap.java:1661) ~[server.jar:?]
        at com.google.common.collect.Iterables$UnmodifiableIterable.forEach(Iterables.java:105) ~[fabric-server-launch.jar:?]
        at net.minecraft.class_3215.method_14161(class_3215.java:327) ~[intermediary-server.jar:?]
        at net.minecraft.class_3215.a(class_3215.java:296) ~[intermediary-server.jar:?]
        at net.minecraft.class_3218.method_18765(class_3218.java:310) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:824) ~[intermediary-server.jar:?]
        ... 5 more
and here is the crash report.
[crash-2019-06-27_23.30.45-server.txt](https://github.com/gnembon/fabric-carpet/files/3336523/crash-2019-06-27_23.30.45-server.txt)
I am using the lastest version of carpet for 1.14.3 and I am trying to test one of my farms

**Comment by gnembon** [comment]
Thanks, will look into that. For now, you can just increase the mobcaps, if what's you want to do is to find the top capacity of your farm/contraption

**Comment by Danielweber2007** [comment]
Thanks.
