### ISSUE TITLE
Incompatibility with Campanion

### ISSUE THREAD

**Issue by decon-structed** [gnembon/fabric-carpet#397]
When creating a new world with Carpet and Campanion installed, the game crashes.

Highlights from the logs:

```
[10:07:01] [main/WARN]: @ModifyConstant conflict. Skipping mixins.reach-entity-attributes.json:ServerPlayerInteractionManagerMixin->@ModifyConstant::modifyReachDistance(D)D with priority 1000, already redirected by carpet.mixins.json:ServerPlayerInteractionManager_antiCheatMixin->@ModifyConstant::addDistance(D)D with priority 69420
[10:07:01] [main/INFO]: [STDERR]: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyReachDistance(D)D in mixins.reach-entity-attributes.json:ServerPlayerInteractionManagerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reach-entity-attributes-refmap.json

...

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 7/30/20 10:07 AM
Description: Starting integrated server

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at

...

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyReachDistance(D)D in mixins.reach-entity-attributes.json:ServerPlayerInteractionManagerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reach-entity-attributes-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
```
The environment:
```
-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 5.4.0-7634-generic
	Java Version: 1.8.0_252, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 1243729688 bytes (1186 MB) / 4550295552 bytes (4339 MB) up to 9544663040 bytes (9102 MB)
	CPUs: 12
	JVM Flags: 2 total; -Xms1024m -Xmx10240m
	Fabric Mods: 
		campanion: Campanion 1.1.13+build.35
		carpet: Carpet Mod in Fabric 1.4.0
		fabric: Fabric API 0.16.2+build.385-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer
``

**Comment by gnembon** [comment]
already fixed in the future version hence closing.
https://github.com/gnembon/fabric-carpet/commit/3f5e2cd2c596eed626906242472f3387ab8dd575
