### ISSUE TITLE
Mixin conflict with Immsersive Portals

### ISSUE THREAD

**Issue by LolHens** [gnembon/fabric-carpet#418]
I found a Mixin conflict with Immersive Portals v0.26+. Happens on dedicated servers and clients.
I have not looked what causes it on their end but maybe these redirects in carpet could somehow be replaced with something more compatible.

```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector relaxMoveRestrictions(Lnet/minecraft/class_3222;)Z in carpet.mixins.json:ServerPlayNetworkHandler_antiCheatDisabledMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json
		at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:400) ~[fabric-server-launch.jar:?]
		at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1280) ~[fabric-server-launch.jar:?]
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[fabric-server-launch.jar:?]
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[fabric-server-launch.jar:?]
		at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
		at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570) ~[fabric-server-launch.jar:?]
		at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
		... 31 more
```

**Comment by Ghoulboy78** [comment]
can you show full crash report?

**Comment by LolHens** [comment]
Sure. I am on MC 1.16.1.
```
08.08.2020  00:09           652.958 fabric-api-0.17.0+build.386-1.16.1.jar
07.08.2020  00:44         1.032.451 fabric-carpet-1.16-1.4.0+v200623.jar
24.08.2020  16:21         1.384.135 immersive-portals-0.27-mc1.16.1-fabric.jar
06.08.2020  15:13           214.103 jumploader-2.0.1.jar
```
https://gist.github.com/LolHens/739ac4778c1342d5aba8f64843ddadf8

**Comment by gnembon** [comment]
https://github.com/gnembon/fabric-carpet/commit/c00cbb72bba1e94cab7fee0dcad60a1a88e6e718
