### ISSUE TITLE
1.16.1 Crash upon attempting to load world. Please Help.

### ISSUE THREAD

**Issue by Kisonu** [gnembon/fabric-carpet#493]
Crash report I get. 

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 10/8/20 3:35 AM
Description: Starting integrated server

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_1132.<init>(class_1132.java:54)
	at net.minecraft.class_310.method_29603(class_310.java:1799)
	at net.minecraft.class_310$$Lambda$5622/821059521.apply(Unknown Source)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:259)
	at net.minecraft.class_310.method_29610(class_310.java:1799)
	at net.minecraft.class_310.method_29609(class_310.java:1772)
	at net.minecraft.class_310$$Lambda$5555/1977468984.run(Unknown Source)
	at net.minecraft.class_310.method_29600(class_310.java:1863)
	at net.minecraft.class_310$$Lambda$5556/1509362921.proceed(Unknown Source)
	at net.minecraft.class_405.method_19792(class_405.java:43)
	at net.minecraft.class_405$$Lambda$5565/1369645058.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$4082/1230814455.run(Unknown Source)
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$4081/1586848556.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3447/783383164.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1044)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method modifyReachDistance(D)D in mixins.reach-entity-attributes.json:ServerPlayerInteractionManagerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap reach-entity-attributes-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:191)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_1132.<init>(class_1132.java:54)
	at net.minecraft.class_310.method_29603(class_310.java:1799)
	at net.minecraft.class_310$$Lambda$5622/821059521.apply(Unknown Source)
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:259)

-- Starting integrated server --
Details:
	Level ID: Modded Survival
	Level Name: Modded Survival
Stacktrace:
	at net.minecraft.class_310.method_29610(class_310.java:1799)
	at net.minecraft.class_310.method_29609(class_310.java:1772)
	at net.minecraft.class_310$$Lambda$5555/1977468984.run(Unknown Source)
	at net.minecraft.class_310.method_29600(class_310.java:1863)
	at net.minecraft.class_310$$Lambda$5556/1509362921.proceed(Unknown Source)
	at net.minecraft.class_405.method_19792(class_405.java:43)
	at net.minecraft.class_405$$Lambda$5565/1369645058.onPress(Unknown Source)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_312$$Lambda$4082/1230814455.run(Unknown Source)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_405
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:431)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_312$$Lambda$4081/1586848556.run(Unknown Source)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at net.minecraft.class_312$$Lambda$3447/783383164.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1044)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6190066392 bytes (5903 MB) / 8482586624 bytes (8089 MB) up to 8482586624 bytes (8089 MB)
	CPUs: 4
	JVM Flags: 27 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -Xms8G -Xmn1024m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
	Fabric Mods: 
		adorn: Adorn 1.10.1+1.16.1
		alwaysdroploot: Always Drop Loot 4.0.0+mc1.16.1
		antiqueatlas: Antique Atlas 5.3.0-fabric
		appleskin: AppleSkin 1.0.11
		artifice: Artifice 0.8.1+1.16.1
		autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
		bedspreads: Bedspreads 1.0.0-1.16.1
		betterbedrockgenerator: Better Bedrock Generator 0.0.8
		betterf3: BetterF3 1.1.1
		betternether: Better Nether 3.5.4
		betterthanmending: BetterThanMending 1.2.0
		blue_endless_jankson: jankson +
		byg: BYG 1.0.13
		caelus: Caelus API 0.0.7-1.16.1
		campanion: Campanion 1.1.13+build.35
		cardinal-components-base: Cardinal Components API (base) 2.4.1
		cardinal-components-entity: Cardinal Components API (entities) 2.4.1
		cardinal-components-item: Cardinal Components API (items) 2.4.1
		cardinal-components-util: Cardinal Components API (utilities) 2.4.1
		carpet: Carpet Mod in Fabric 1.4.0
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.0.4
		cloth-config2: Cloth Config v4 4.6.0
		colytra: Colytra 1.0.1-1.16.1
		compact-storage: CompactStorage 4.0.0
		cotton: Cotton 1.0.7
		cotton-cauldron: Cotton Cauldron 1.0.4
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		cotton-resources: Cotton Resources 1.7.1
		curioofundying: Curio of Undying 1.16.1-1.0
		curios: Curios API 1.16.1-0.5
		curiouselytra: Curious Elytra 1.0.0-1.16.1
		curiousshulkerboxes: Curious Shulker Boxes 1.16.1-1.0
		diggusmaximus: Diggus Maximus 1.3.0-1.16
		ducts: Ducts 1.0.1
		endreborn: End: Rebellion 1.7.1
		expandedconcrete: Expanded Concrete 0.0.2
		extrapieces: Extra Pieces 2.9.0
		ezpas: Ezpas 1.2.1-1.16.1
		fabric: Fabric API 0.17.0+build.386-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.7+2242e77202
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+be551d3c02
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+91fca5cd02
		fabricloader: Fabric Loader 0.9.2+build.206
		fiber: fiber 0.23.0-2
		infinitevillagertrading: InfiniteVillagerTrading 1.16-fabric0.13.1-1.0.2
		infinityfix: Infinity Fix 1.1.0
		inmis: Inmis 1.2.0-1.16.1
		jankson: Jankson 3.0.0+j1.2.0
		justupgrade: Just Upgrade 1.0.2
		kibe: Kibe 1.1.12-BETA
		kyrptconfig: Kytpt Config 1.1.0-1.16
		libblockattributes_core: LibBlockAttributes (Core) 0.7.0
		libblockattributes_items: LibBlockAttributes (Items) 0.7.0
		libcd: LibCapableData 2.4.1+1.16-pre2
		libgui: LibGui 2.2.0+1.16.1
		libstructure: Libstructure 1.3
		lithium: Lithium 0.5.1
		logical_zoom: Logical Zoom 0.0.4
		mcf-reap: MaxVar reap for fabric 1.4.0
		minecraft: Minecraft 1.16.1
		modmenu: Mod Menu 1.14.5+build.30
		netheriteshulkers: Netherite Shulkers 0.0.1
		nomoreglowingpots: No More Glowing Pots 1.0.2
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		parchment: Parchment 1.0.2+1.15.2
		phosphor: Phosphor 0.6.0+build.7
		playerabilitylib: Pal 1.2.0
		portaltags: Portal Tags 1.0.0+1.16.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		redstonebits: Redstone Bits 1.2.2
		roughlyenoughitems: Roughly Enough Items 4.12.1
		sbinnery: Sbinnery 12.2
		shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
		silky_spawners: Silky Spawners 2.0.0+build.1-1.16
		slotlink: slotlink 1.2.5+minecraft-1.16.1
		sodium: Sodium 0.1.0
		soulbound: Soulbound 1.0.1
		soulsandstone: Soul Sandstone 0.0.2
		spinnery: Spinnery 3.1.12
		stairdoors-fabric: StairDoors Fabric 2.1.0
		stockpile: Stockpile 1.1.5+1.16.1
		universalcomponents: Universal Components 0.7.2+1.16-pre2
		vanillaautomated: Vanilla Automated 1.1.2
		waila: Hwyla 1.9.22
	Launched Version: fabric-loader-0.9.2+build.206-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon R7 Graphics GL version 4.5.13476 Compatibility Profile Context 22.19.180.513, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: vanilla (incompatible), extrapieces:ep_assets, file/Variant_Grass_1.1 [1.15].zip, file/VanillaTweaks_r738776.zip (incompatible)
	Current Language: English (US)
	CPU: 4x AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G

**Comment by Ghoulboy78** [comment]
use 1.16.3

**Comment by gnembon** [comment]
this has been fixed already, please update yo carpet.
