### ISSUE TITLE
1.14.3 version

### ISSUE THREAD

**Issue by vkorn** [gnembon/fabric-carpet#52]
I'm trying to run a 1.14.3 released version and getting the following crash upon start
```
[14:18:48] [main/WARN]: Mixin config carpet.mixins.json does not specify "minVersion" property
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:51)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:107)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:63)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105)
        ... 1 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61)
        ... 2 more
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:172)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
        ... 7 more
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
        ... 9 more
Caused by: java.lang.IncompatibleClassChangeError: Method net.minecraft.class_2357.handler$addBlockRotator$zcm000(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V must be InterfaceMethodref constant
        at net.minecraft.class_2357.method_18346(class_2357.java)
        at net.minecraft.class_2966.method_12851(class_2966.java:53)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:897)
        ... 14 more
```

Building from the sources with the latest source code (for 14.4pre4) gives similar error. Doesn't matter whether external server is used or `./gradlew runServer`. Am I missing something?

**Comment by cdemasy** [comment]
Same issue here, completely fresh install.

**Comment by imitatertsh** [comment]
+1(for 14_3)

**Comment by VictorAlbertsson** [comment]
+1 (1.14.3)
```
Exception in thread "Client thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:172)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	... 2 more
Caused by: java.lang.IncompatibleClassChangeError: Method 'void net.minecraft.class_2357.handler$addBlockRotator$zgh000(org.spongepowered.asm.mixin.injection.callback.CallbackInfo)' must be InterfaceMethodref constant
	at net.minecraft.class_2357.method_18346(class_2357.java)
	at net.minecraft.class_2966.method_12851(class_2966.java:53)
	at net.minecraft.class_310.<init>(class_310.java:384)
	at net.minecraft.client.main.Main.main(Main.java:154)
	... 7 more
```

**Comment by VictorAlbertsson** [comment]
Tested on 1.14.4-pre5 Linux/Debian with MultiMC and it works.

**Comment by imitatertsh** [comment]
> 使用MultiMC在1.14.4-pre5 Linux / Debian上进行测试，它可以正常工作。

I tested on 1.14.3 ubuntu

**Comment by gnembon** [comment]
Could you give me more context in terms of
 - environment (client / server)
 - which mc version
 - which carpet version

Its also not clear if it 'works' in 1.14.4-pre5 meaning it 'also crashes' or 'not crashing anymore'

**Comment by vkorn** [comment]
@gnembon 

I'm not sure about others, but I'm trying to run either
1. Published by you 14.3 version or
2. Latest source code version (tried just now)

I've tried both dedicated server.jar and runServer task. 

Here's what I'm getting with latest sources

```
> Task :runServer
[12:52:08] [main/INFO]: Loading for game Minecraft 1.14.4 Pre-Release 6
[12:52:08] [main/INFO]: [FabricLoader] Loading 2 mods: fabricloader@0.4.8+build.155, carpet@1.14.4-pre6-1.0.0+v190707
[12:52:08] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/Users/vkorn/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.7.11.36/b0d9944f2b77f1ce952a1179e595037332910a82/sponge-mixin-0.7.11.36.jar Service=Knot/Fabric Env=SERVER
[12:52:09] [main/INFO]: Loaded Fabric development mappings for mixin remapper!
[12:52:09] [main/INFO]: Compatibility level set to JAVA_8
[12:52:09] [main/WARN]: Mixin config carpet.mixins.json does not specify "minVersion" property
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:172)
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
        ... 2 more
Caused by: java.lang.IncompatibleClassChangeError: Method net.minecraft.block.dispenser.DispenserBehavior.handler$addBlockRotator$zda000(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V must be InterfaceMethodref constant
        at net.minecraft.block.dispenser.DispenserBehavior.registerDefaults(DispenserBehavior.java)
        at net.minecraft.Bootstrap.initialize(Bootstrap.java:44)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:912)
        ... 7 more

> Task :runServer FAILED

FAILURE: Build failed with an exception.
```

**Comment by timaxlucas** [comment]
Client side works fine for me, although I am getting the same error as in the original post when running on fabric server. Tried on 1.14.3 and 1.14.4 pre 6 with the same crash.

Running on Ubuntu 14.04.6 with Java 11.0.2 and fabric-carpet v19_07_07 for 1.14.4 pre 6 and v19_06_24 for 1.14.3.

**Comment by ltschall** [comment]
I encountered the same error. For me switching to JRE Version 1.8 fixed it.

In conclusion:
Java 11 -> IncompatibleClassChangeError
Java 8 -> all working fine

**Comment by timaxlucas** [comment]
@ltschall Yes, I just downgraded my server to java 1.8 and this fixed the issue.

**Comment by VictorAlbertsson** [comment]
I have also tested it on 1.14.4-pre6 and it does not crash.

I'm using MultiMC 5 0.6.6-1256
with Minecraft 1.14.4-pre5
and Carpet 1.14.4-pre5
on Fabric 0.4.8+build.155
also I'm running Java 11.0.4-ea (OpenJDK)
