### ISSUE TITLE
Carpet collision crash with ViaVersion 20w49a

### ISSUE THREAD

**Issue by LordCandyAndy** [gnembon/fabric-carpet#607]
[crash-2020-12-04_21.37.25-server.txt](https://github.com/gnembon/fabric-carpet/files/5645329/crash-2020-12-04_21.37.25-server.txt)

```
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 12/4/20 9:37 PM
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access field net.minecraft.class_1657.field_7503 from class net.minecraft.class_3244
	at net.minecraft.class_3244.checkMove(class_3244.java:4040)
	at net.minecraft.class_3244.handler$zbe000$checkMovement(class_3244.java:3873)
	at net.minecraft.class_3244.method_12063(class_3244.java:808)
	at net.minecraft.class_2828.method_12272(class_2828.java:122)
	at net.minecraft.class_2828$class_2830.method_11054(class_2828.java:18)
	at net.minecraft.class_2600.method_11072(class_2600.java:21)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:144)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:760)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:157)
	at net.minecraft.class_1255.method_16075(class_1255.java:118)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:736)
	at net.minecraft.class_1255.method_18857(class_1255.java:127)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721)
	at net.minecraft.server.MinecraftServer.handler$zfh000$modifiedRunLoop(MinecraftServer.java:3317)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 20w49a
	Minecraft Version ID: 20w49a
	Operating System: Linux (amd64) version 3.10.0-1127.19.1.el7.x86_64
	Java Version: 1.8.0_262, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1939163256 bytes (1849 MB) / 3221225472 bytes (3072 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 2
	JVM Flags: 20 total; -Xms3G -Xmx3G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 2.2.0
		carpet: Carpet Mod in Fabric 1.4.20
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.10
		com_squareup_okhttp3_okhttp: okhttp 3.13.0
		com_squareup_okio_okio: okio 1.17.2
		com_vdurmont_emoji-java: emoji-java 5.1.1
		fabric: Fabric API 0.27.2+1.17
		fabric-api-base: Fabric API Base 0.2.0+eaafab806c
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+f1dfa4ca6c
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+9f7a74236c
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+9f7a74236c
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+9f7a74236c
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+880269e66c
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d6c
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+e1f1abb16c
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.3+9f7a74236c
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+9f7a74236c
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.4+3e817a626c
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+9f7a74236c
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+9f7a74236c
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.3.3+880269e66c
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+0c3d83a56c
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+9f7a74236c
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.6+9f7a74236c
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+9f7a74236c
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.2+9f7a74236c
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+9f7a74236c
		fabric-particles-v1: fabric-particles-v1 0.2.2+9f7a74236c
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.1+18e7e5e16c
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+9f7a74236c
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.5+e1f1abb16c
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.3+9f7a74236c
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.2+cc3cc6c66c
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+e1f1abb16c
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.7+9f7a74236c
		fabricloader: Fabric Loader 0.10.8
		fabricproxy: FabricProxy 1.3.3
		fdlink: Fabric <-> Discord Link 0.7.18
		fdlink_1_15_2: Fabric <-> Discord Link 0.7.18
		fdlink_1_16: Fabric <-> Discord Link 0.7.18
		fdlink_common: Fabric <-> Discord Link 0.7.18
		golfiv: Golf IV 0.0.1
		minecraft: Minecraft 1.17-alpha.20.49.a
		net_dv8tion_jda: JDA 4.2.0_191
		net_sf_trove4j_trove4j: trove4j 3.0.3
		org_apache_commons_commons-collections4: commons-collections4 4.1
		org_json_json: json 20170516
		org_slf4j_slf4j-api: slf4j-api 1.7.25
		org_slf4j_slf4j-nop: slf4j-nop 1.7.25
		org_yaml_snakeyaml: snakeyaml 1.26
		viabackwards: ViaBackwards 3.3.0-20w49a
		viafabric: ViaFabric 0.2.16-SNAPSHOT+build-608.1-mc-1.16
		viaversion: ViaVersion 3.3.0-20w49a
	Player Count: 2 / 25; [class_3222['LordCandyAndy'/154, l='ServerLevel[world]', x=113.70, y=60.00, z=31.70], class_3222['LordCandy2687'/1218, l='ServerLevel[world]', x=142.34, y=65.77, z=90.02]]
	Data Packs: vanilla, file/OnePlayerSleepV42 .zip (incompatible), file/afk display v1.1.0.zip (incompatible), fabric/fabric-tool-attribute-api-v1
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by gnembon** [comment]
Please specify where did you get that ViaVersion 3.3.0-20w49a from  - can't find a relevant download.

**Comment by LordCandyAndy** [comment]
Latest Viaversion-DEV:
https://ci.viaversion.com/job/ViaVersion-DEV/
Used with ViaBackwards 20w49a:
https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-DEV/237/

**Comment by LordCandyAndy** [comment]
Accidentally closed on mobile sorry

**Comment by gnembon** [comment]
![Capture](https://user-images.githubusercontent.com/41132274/101270269-e772c500-374d-11eb-9b42-f38bb8c2283b.PNG)
don't see an issue - runs fine - its probably some other mod on your list.

**Comment by LordCandyAndy** [comment]
Appears to be from GolfIV, which does not support the latest 1.17 snapshots
