### ISSUE TITLE
Crash caused by optimized tnt

### ISSUE THREAD

**Issue by Devon7925** [gnembon/fabric-carpet#728]
```
20.02 23:34:58 [Server] Server thread/ERROR Encountered an unexpected exception
20.02 23:34:58 [Server] INFO net.minecraft.class_148: Ticking entity
20.02 23:34:58 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:875) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.class_3176.method_3813(class_3176.java:312) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.server.MinecraftServer.handler$zbb000$modifiedRunLoop(MinecraftServer.java:2310) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
20.02 23:34:58 [Server] INFO Caused by: java.lang.NullPointerException
20.02 23:34:58 [Server] INFO at carpet.helpers.OptimizedExplosion.doExplosionA(OptimizedExplosion.java:121) ~[fabric-carpet-1.16.5-1.4.27+v210217.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.class_1927.handler$zeg000$onExplosionA(class_1927.java:543) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.class_1927.method_8348(class_1927.java) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.class_3218.method_8454(class_3218.java:1031) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.class_1937.method_8537(class_1937.java:577) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.class_1674.method_7488(class_1674.java:35) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.class_1668.method_5773(class_1668.java:77) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.class_3218.method_18762(class_3218.java:621) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.class_1937.method_18472(class_1937.java:561) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.class_3218.method_18765(class_3218.java:411) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:871) ~[intermediary-server.jar:?]
20.02 23:34:58 [Server] INFO ... 6 more
```

**Comment by James103** [comment]
1. Do you have the full crash report? If so, can you please post it here?
2. How did you reproduce this issue?

**Comment by Devon7925** [comment]
1. Not anymore but I think its pretty clearly a problem at OptimizedExplosion.java:121 likely with eAccess.getEntity() being null 
2.It consistently happened on my server when optimized tnt was enabled, not sure why it would occur on my server and not other places. Carpet mod was only mod although I did make some changes to tnt behavior via datapacks.

**Comment by gnembon** [comment]
makes sense - the entity causing the explosion can be null (beds for example).
