### ISSUE TITLE
Minecraft 1.14.4 wont start with carpet 1.0.3

### ISSUE THREAD

**Issue by F0Xde** [gnembon/fabric-carpet#74]
If I try to start Minecraft 1.14.4 with carpet 1.0.3, the game always crashes. I already removed all my other mods and tried with/without the fabric-api.
Here's the stacktrace:
```
Exception in thread "Client thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:172)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
	... 2 more
Caused by: java.lang.IncompatibleClassChangeError: Method 'void net.minecraft.class_2357.handler$addBlockRotator$zdc000(org.spongepowered.asm.mixin.injection.callback.CallbackInfo)' must be InterfaceMethodref constant
	at net.minecraft.class_2357.method_18346(class_2357.java)
	at net.minecraft.class_2966.method_12851(class_2966.java:53)
	at net.minecraft.class_310.<init>(class_310.java:383)
	at net.minecraft.client.main.Main.main(Main.java:155)
	... 7 more
```
I am btw running the mod client-side, maybe its a server-only mod? If so, please specify that in the README.

**Comment by TIVJ-dev** [comment]
For me it runs just fine. Did you use the fresh jar from releases, or did you compile it yourself (if you did compile it, it could maybe be a Gradle issue)?
Probably the issue here is that your Java version is too new/old. I use version 1.8.0_211

**Comment by F0Xde** [comment]
> For me it runs just fine. Did you use the fresh jar from releases, or did you compile it yourself (if you did compile it, it could maybe be a Gradle issue)?
> Probably the issue here is that your Java version is too new/old. I use version 1.8.0_211
> 
> It is NOT a server-only mod, and doesn't need Fabric API (however other mods might need it)

Oh i totally forgot to check other java versions, indeed it works fine with Java 8. Ty
