### ISSUE TITLE
Null pointer exception crash when leaving singleplayer world

### ISSUE THREAD

**Issue by Mystixs3** [gnembon/fabric-carpet#776]
This might already have an issue but when I left my singleplayer world this crash happened. I was using `fabric-carpet-1.16.5-1.4.27+v210217` and updating to `fabric-carpet-1.16.5-1.4.29+v210310` seemed to fix it. I was using MultiMC but I don't think that caused it but whatever. I was also using JDK 15 with ZGC. The crash report is below:

```---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 27/03/2021, 10:27
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot invoke "carpet.logging.Logger.log(java.util.function.Supplier)" because the return value of "carpet.logging.LoggerRegistry.getLogger(String)" is null
	at Not Enough Crashes deobfuscated stack trace.(1.16.5+build.5)
	at carpet.logging.HUDController.update_hud(HUDController.java:71)
	at carpet.CarpetServer.tick(CarpetServer.java:115)
	at net.minecraft.server.MinecraftServer.handler$cla000$onTick(MinecraftServer:6716)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer:811)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer:91)
	at net.minecraft.server.MinecraftServer.handler$clb000$modifiedRunLoop(MinecraftServer:7310)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:651)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:257)
	at java.lang.Thread.run(Thread.java:832)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 15.0.2, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 1088421888 bytes (1038 MB) / 4200595456 bytes (4006 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 12
	JVM Flags: 4 total; -XX:+UseZGC -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1024m -Xmx4096m
	Suspected Mods: Carpet Mod in Fabric (carpet)
	Fabric Mods: 
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.9
		antighost: AntiGhost 1.16.5-fabric0.30.0-1.1.3
		appleskin: AppleSkin 1.0.11
		autoconfig1u: Auto Config v1 Updated 3.3.1
		autoconfigtoml: AutoConfig-TOML 1.0.0-fabric
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		c2me: Concurrent Chunk Management Engine 0.1-SNAPSHOT
		cardinal-components-base: Cardinal Components API (base) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.6.0
		carpet: Carpet Mod in Fabric 1.4.27
		carpet-extra: Carpet Extra 1.4.27
		carpet-tis-addition: Carpet TIS Addition 1.13.0
		chime: Chime 1.1.2
		cleardespawn: Clear Despawn 1.16.5-fabric0.30.0-1.1.1
		clickthrough: ClickThrough 1.16.5-fabric0.30.0-0.3
		clientcommands: Client Commands 2.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.5.47
		cloth-config2: Cloth Config v4 4.11.14
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_github_wearblackallday_javautils: JavaUtils ab1e0ad736be1d2c2d74c68fa8e9e40e752f2d18
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		crowdin-translate: CrowdinTranslate 1.2
		customsplashscreen: Custom Splash Screen 1.0.0
		dimthread: DimensionalThreading 1.2.2
		dynamicfps: Dynamic FPS 2.0.1
		entityculling: EntityCulling-Fabric 1.0.2
		fabric: Fabric API 0.31.0+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.0+f9b3753b7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.2
		fabrishot: Fabrishot 1.2.3.1
		fastfurnace: FastFurnace 2.3
		fedora: Fedora 1.1.1-fabric-1.16.4
		ferritecore: FerriteCore 2.0.1
		fiber: fiber 0.23.0-2
		gbfabrictools: GBfabrictools 1.3.2+1.16.4
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		itemscroller: Item Scroller 0.15.0-dev.20210111.205029
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 15
		keepheadnames: Keep Head Names 1.1
		krypton: Krypton 0.1.2
		lambdynlights: LambDynamicLights 1.3.4+1.16
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 3.1.0+1.16.3
		litematica: Litematica 0.0.0-dev.20210120.213004
		lithium: Lithium 0.6.4
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		minecraft: Minecraft 1.16.5
		minihud: MiniHUD 0.19.0-dev.20201103.184029
		modmenu: Mod Menu 1.16.8
		modupdater: ModUpdater 1.1.11+1.16.2-rc2
		multiconnect-api: MultiConnect API 1.3.9
		nameless_servers: Nameless Servers 1.0.0
		nbtcrafting: NBT Crafting 2.0.5+mc1.16.4
		notenoughcrashes: Not Enough Crashes 3.1.5
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		overworld_two: Overworld 2 1.0.4
		paradoxslabs: ParadoxSlabs 0.1.0
		petowner: Pet Owner 1.7.1-1.16.2+
		randompatches: RandomPatches 2.4.5-fabric
		roughlyenoughitems: Roughly Enough Items 5.10.183
		roughlyenoughitems-api: REI (API) 5.10.183
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.10.183
		roughlyenoughitems-runtime: REI (Runtime) 5.10.183
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		shulkerboxtooltip: Shulker Box Tooltip 2.3.5+1.16.5
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		sodium: Sodium 0.1.0
		sodium-extra: Sodium Extra 0.2.2
		spruceui: SpruceUI 2.0.4+1.16
		stairdoors-fabric: StairDoors Fabric 2.1.0
		starlight: Starlight 0.0.3
		tweakeroo: Tweakeroo 0.10.0-dev.20210209.145902
		wither_cage_fix: Mod Name 1.0.4+MC1.16.1-1.16.5
		worldborderfix: Worldborderfix 1.0-SNAPSHOT-fabric-1.16.5
		worldedit: WorldEdit 7.2.3+5680-135941e
		worldeditcui: WorldEditCUI 1.16.5+02
		wthit: wthit 2.2.1+1.16.5
		xaerominimap: Xaero's Minimap 21.4.2
		xaeroworldmap: Xaero's World Map 1.12.2
	Player Count: 1 / 8; [class_3222['Mystixs3'/2117, l='ServerLevel[Survival]', x=7.70, y=63.09, z=592.12]]
	Data Packs: vanilla (incompatible), Fabric Mods
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
```

**Comment by altrisi** [comment]
IIRC yeah, this was fixed in the latest version, or at least in the dev builds.
