### ISSUE TITLE
[Mixin Error]detected, disabling UPDATE mixin com.sk89q.worldedit.fabric.mixin.MixinWorldChunkSetBlockHook

### ISSUE THREAD

**Issue by Phoupraw** [gnembon/fabric-carpet#779]
It crashes before game launches every time.
```Command: "C:\\Program Files\\Java\\jdk1.8.0_171\\jre\\bin\\java.exe" -Dminecraft.client.jar=.minecraft\versions\1.16.5\1.16.5.jar -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx4096m -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump "-Djava.library.path=D:\\Entertainments\\Minecraft 原版\\.minecraft\\versions\\1.16.5\\natives" -Dminecraft.launcher.brand=HMCL -Dminecraft.launcher.version=3.3.172 -cp "D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\net\\fabricmc\\tiny-mappings-parser\\0.2.2.14\\tiny-mappings-parser-0.2.2.14.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\net\\fabricmc\\sponge-mixin\\0.8.2+build.24\\sponge-mixin-0.8.2+build.24.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\net\\fabricmc\\tiny-remapper\\0.3.0.70\\tiny-remapper-0.3.0.70.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\net\\fabricmc\\access-widener\\1.0.0\\access-widener-1.0.0.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\net\\fabricmc\\fabric-loader-sat4j\\2.3.5.4\\fabric-loader-sat4j-2.3.5.4.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\com\\google\\jimfs\\jimfs\\1.2-fabric\\jimfs-1.2-fabric.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\ow2\\asm\\asm\\9.0\\asm-9.0.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\ow2\\asm\\asm-analysis\\9.0\\asm-analysis-9.0.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\ow2\\asm\\asm-commons\\9.0\\asm-commons-9.0.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\ow2\\asm\\asm-tree\\9.0\\asm-tree-9.0.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\ow2\\asm\\asm-util\\9.0\\asm-util-9.0.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\com\\google\\guava\\guava\\21.0\\guava-21.0.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\net\\fabricmc\\intermediary\\1.16.5\\intermediary-1.16.5.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\net\\fabricmc\\fabric-loader\\0.11.1\\fabric-loader-0.11.1.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\com\\mojang\\patchy\\1.1\\patchy-1.1.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\oshi-project\\oshi-core\\1.1\\oshi-core-1.1.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\net\\java\\dev\\jna\\jna\\4.4.0\\jna-4.4.0.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\net\\java\\dev\\jna\\platform\\3.4.0\\platform-3.4.0.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\com\\ibm\\icu\\icu4j\\66.1\\icu4j-66.1.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\com\\mojang\\javabridge\\1.0.22\\javabridge-1.0.22.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\net\\sf\\jopt-simple\\jopt-simple\\5.0.3\\jopt-simple-5.0.3.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\io\\netty\\netty-all\\4.1.25.Final\\netty-all-4.1.25.Final.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\apache\\commons\\commons-lang3\\3.5\\commons-lang3-3.5.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\commons-io\\commons-io\\2.5\\commons-io-2.5.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\commons-codec\\commons-codec\\1.10\\commons-codec-1.10.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\net\\java\\jinput\\jinput\\2.0.5\\jinput-2.0.5.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\net\\java\\jutils\\jutils\\1.0.0\\jutils-1.0.0.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\com\\mojang\\brigadier\\1.0.17\\brigadier-1.0.17.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\com\\mojang\\datafixerupper\\4.0.26\\datafixerupper-4.0.26.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\com\\google\\code\\gson\\gson\\2.8.0\\gson-2.8.0.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\com\\mojang\\authlib\\2.1.28\\authlib-2.1.28.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\apache\\commons\\commons-compress\\1.8.1\\commons-compress-1.8.1.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\apache\\httpcomponents\\httpclient\\4.3.3\\httpclient-4.3.3.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\commons-logging\\commons-logging\\1.1.3\\commons-logging-1.1.3.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\apache\\httpcomponents\\httpcore\\4.3.2\\httpcore-4.3.2.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\it\\unimi\\dsi\\fastutil\\8.2.1\\fastutil-8.2.1.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\apache\\logging\\log4j\\log4j-api\\2.8.1\\log4j-api-2.8.1.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\apache\\logging\\log4j\\log4j-core\\2.8.1\\log4j-core-2.8.1.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\lwjgl\\lwjgl\\3.2.2\\lwjgl-3.2.2.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-jemalloc\\3.2.2\\lwjgl-jemalloc-3.2.2.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-openal\\3.2.2\\lwjgl-openal-3.2.2.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-opengl\\3.2.2\\lwjgl-opengl-3.2.2.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-glfw\\3.2.2\\lwjgl-glfw-3.2.2.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-stb\\3.2.2\\lwjgl-stb-3.2.2.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\org\\lwjgl\\lwjgl-tinyfd\\3.2.2\\lwjgl-tinyfd-3.2.2.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\libraries\\com\\mojang\\text2speech\\1.11.3\\text2speech-1.11.3.jar;D:\\Entertainments\\Minecraft 原版\\.minecraft\\versions\\1.16.5\\1.16.5.jar" net.fabricmc.loader.launch.knot.KnotClient --username Phoupraw --version "HMCL 3.3.172" --gameDir "D:\\Entertainments\\Minecraft 原版\\.minecraft\\versions\\1.16.5" --assetsDir "D:\\Entertainments\\Minecraft 原版\\.minecraft\\assets" --assetIndex 1.16 --uuid 83e76e80416b4baab16813a561360860 --accessToken eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1ZTdjM2M2ZDYxNjNhMWQwODNhYzdjNmI4MmFlMzlhYyIsInlnZ3QiOiIxZjU4ZWMxNzQ0NWU0YTNhYTUxOGY3MDc3MzBjNGFmNCIsInNwciI6IjgzZTc2ZTgwNDE2YjRiYWFiMTY4MTNhNTYxMzYwODYwIiwiaXNzIjoiWWdnZHJhc2lsLUF1dGgiLCJleHAiOjE2MTcxODQ4OTIsImlhdCI6MTYxNzAxMjA5Mn0.N90-IPs2aUXx2x1L0xyiTTu2AZDibnAL1kM3gjAHrEI --userType mojang --versionType "HMCL 3.3.172" --width 854 --height 480
[12:03:59] [main/INFO]: Loading for game Minecraft 1.16.5
[12:03:59] [ForkJoinPool-1-worker-14/WARN]: Non-Fabric mod JAR at "D:\Entertainments\Minecraft 原版\.minecraft\versions\1.16.5\mods\MixinBootstrap-1.0.4.jar", ignoring
[12:03:59] [ForkJoinPool-1-worker-6/WARN]: Non-Fabric mod JAR at "D:\Entertainments\Minecraft 原版\.minecraft\versions\1.16.5\mods\【砂砾终结者】GravelMiner_1.16.3-10.2.0.jar", ignoring
[12:03:59] [ForkJoinPool-1-worker-13/WARN]: Non-Fabric mod JAR at "D:\Entertainments\Minecraft 原版\.minecraft\versions\1.16.5\mods\【极简血量显示-Forge】Neat+1.7-24.jar", ignoring
[12:03:59] [main/WARN]: Warnings were found! 
 - Mod 'Giselbaers Durability Viewer' (durabilityviewer) recommends version 1.1.7 or later of mod modupdater, which is missing!
	 - You must install version 1.1.7 or later of modupdater.
[12:03:59] [main/INFO]: [FabricLoader] Loading 71 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, gbfabrictools@1.2.3+1.16.2, fabricloader@0.11.1, inventoryprofiles@0.4.2, fabric-structure-api-v1@1.1.4+ca58154a7d, fabric-containers-v0@0.1.11+9354966b7d, fabric-dimensions-v1@2.0.6+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, java@8, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.1+9354966b7d, libblockattributes@0.8.7, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, fabric-textures-v0@1.0.6+ca58154a7d, tweakeroo@0.10.0-dev.20201004.191811, worldeditcui@1.16.5+02, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, litematica@0.0.0-dev.20200920.161640, waila@1.9.22, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, sodium@0.1.0, fabric-renderer-registries-v1@2.2.1+ca58154a7d, libblockattributes_items@0.8.7, minihud@0.19.0-dev.20200928.220110, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric@0.32.5+1.16, carpet@1.4.29, fabric-particles-v1@0.2.4+ca58154a7d, libblockattributes_core@0.8.7, fabric-networking-v0@0.3.2+ca58154a7d, tellme@0.9.0-alpha.1, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, minecraft@1.16.5, fabric-screen-handler-api-v1@1.1.5+9354966b7d, modmenu@1.14.6+build.31, cloth-basic-math@0.5.1, fabric-command-api-v1@1.1.1+351679a77d, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, fabric-renderer-indigo@0.4.4+ca58154a7d, autofish@0.9.0, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-key-binding-api-v1@1.0.4+9354966b7d, fabric-rendering-v1@1.5.1+ca58154a7d, cloth-config2@4.7.0-unstable, fabric-resource-loader-v0@0.4.2+ca58154a7d, malilib@0.10.0-dev.21+arne.1, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, worldedit@7.2.4+5723-e3bfc64, fabric-biome-api-v1@3.1.1+ca58154a7d, libblockattributes_fluids@0.8.7, fabric-commands-v0@0.2.2+ca58154a7d, fabric-registry-sync-v0@0.7.4+ca58154a7d, durabilityviewer@1.16.2-fabric0.17.2-1.8.7, itemscroller@0.15.0-dev.20200912.221805, fabric-mining-levels-v0@0.1.3+ca58154a7d, voxelmap@1.10.11, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, masa_gadget_mod@1.16.1-1.0.1-alpha.1, fabric-models-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.5+351679a77d, fabric-object-builders-v0@0.7.2+ca58154a7d
[12:03:59] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/D:/Entertainments/Minecraft%20%e5%8e%9f%e7%89%88/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8.2+build.24/sponge-mixin-0.8.2+build.24.jar Service=Knot/Fabric Env=CLIENT
[12:03:59] [main/INFO]: Loaded configuration file for Sodium (38 options available, 0 user overrides)
[12:03:59] [main/INFO]: Sodium has been successfully discovered and initialized -- your game is now faster!
[12:03:59] [main/WARN]: [carpet] detected, disabling UPDATE mixin com.sk89q.worldedit.fabric.mixin.MixinWorldChunkSetBlockHook
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:228)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	... 2 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_2246.<clinit>(class_2246.java:835)
	at net.minecraft.class_3523.<clinit>(class_3523.java:13)
	at net.minecraft.class_5471.<clinit>(class_5471.java:11)
	at net.minecraft.class_5458.method_30573(class_5458.java:44)
	at net.minecraft.class_5458.method_30566(class_5458.java:75)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at net.minecraft.class_5458.<clinit>(class_5458.java:74)
	at net.minecraft.class_2378.<clinit>(class_2378.java:237)
	at net.minecraft.class_2966.method_12851(class_2966.java:42)
	at net.minecraft.client.main.Main.main(Main.java:137)
	... 7 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method outlineRenderDistanceLimit(D)D in carpet.mixins.json:StructureBlockBlockEntity_limitsMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 23 more
```

**Comment by altrisi** [comment]
Since this is not the worldedit compat that was fixed not long again (that is not the error), and since this is complaining about the structure block limits mixin, I'd say this is because you are using an outdated version of tweakeroo, try updating it to the latest development build and if it doesn't work, provide the crash report instead of the log.

**Comment by altrisi** [comment]
Also note that MixinBootstrap is a forge mod (Mixin is the base of Fabric already, therefore included), and you have two other non-fabric mods.

**Comment by Phoupraw** [comment]
> Since this is not the worldedit compat that was fixed not long again (that is not the error, it's just informing you of the behaviour), and since this is complaining about the structure block limits mixin, I'd say this is because you are using an outdated version of tweakeroo, try updating it to the latest development build and if it doesn't work, provide the crash report instead of the log, it should be there somewhere.

It launches normally after I update twewkeroo. Thank you very much!

**Comment by DragonEggBedrockBreaking** [comment]
> It launches normally after I update twewkeroo. Thank you very much!

So this should be closed?
