### ISSUE TITLE
 [suggest] Compatible java11

### ISSUE THREAD

**Issue by 1a2s3d4f1** [gnembon/fabric-carpet#79]
Could you compatible java11 in future?
fabric carpet does not work in java11.

crash log:

```
Exception in thread "Client thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:180)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	... 2 more

Caused by: java.lang.IncompatibleClassChangeError: Method net.minecraft.class_2357.handler$addBlockRotator$zdd000(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V must be InterfaceMethodref constant
	at net.minecraft.class_2357.method_18346(class_2357.java)
	at net.minecraft.class_2966.method_12851(class_2966.java:53)
	at net.minecraft.class_310.<init>(class_310.java:383)
	at net.minecraft.client.main.Main.main(Main.java:155)
	... 7 `more`


```

**Comment by gnembon** [comment]
This has been fixed a few hours before your bug report, but thank you for submitting it anyways.
https://github.com/gnembon/fabric-carpet/pull/78
This will be fixed in the next release. Bug comes from the mixin engine not compatible with Java9+, and minecraft requires Java 8, so I would say that running the game with Java 9+ is experimental.
