### ISSUE TITLE
[Bug]In the server ,using /counter will kill the server,when hopperCounter counts bone_meal

### ISSUE THREAD

**Issue by xiaoshengu** [gnembon/fabric-carpet#864]
In the server ,using /counter will kill the server,when hopperCounter counts bone_meal
Release version：1.14.33+
[2021-05-17-7.log](https://github.com/gnembon/fabric-carpet/files/6491644/2021-05-17-7.log)

**Comment by keuin** [comment]
I also encountered this bug. Here is my log:

```
[20:43:20] [Server thread/INFO]: [Borbal: Restarted orange counter]
[21:05:28] [Server thread/INFO]: [Borbal: Current tps is: 20.0]
[21:11:52] [Server thread/INFO]: [Borbal: Restarted red counter]
[21:15:14] [Server thread/INFO]: [Borbal: Restarted red counter]
[21:17:00] [Server thread/INFO]: [Borbal: Killed 95 entities]
[21:24:03] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'boolean net.minecraft.class_2348.method_10250(net.minecraft.class_2960)'
	at carpet.helpers.HopperCounter.fromItem(HopperCounter.java:282) ~[fabric-carpet-1.16.5-1.4.33+v210421.jar:?]
	at carpet.helpers.HopperCounter.guessColor(HopperCounter.java:297) ~[fabric-carpet-1.16.5-1.4.33+v210421.jar:?]
	at carpet.helpers.HopperCounter.lambda$format$1(HopperCounter.java:164) ~[fabric-carpet-1.16.5-1.4.33+v210421.jar:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at carpet.helpers.HopperCounter.format(HopperCounter.java:171) ~[fabric-carpet-1.16.5-1.4.33+v210421.jar:?]
	at carpet.commands.CounterCommand.displayCounter(CounterCommand.java:45) ~[fabric-carpet-1.16.5-1.4.33+v210421.jar:?]
	at carpet.commands.CounterCommand.lambda$register$3(CounterCommand.java:29) ~[fabric-carpet-1.16.5-1.4.33+v210421.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[intermediary-server_1.16.5.jar:?]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.class_2170.method_9249(class_2170.java:249) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.class_3244.method_14370(class_3244.java:1211) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.class_3244.method_31286(class_3244.java:1198) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.class_3244.method_12048(class_3244.java:1177) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.class_2797.method_12115(class_2797.java:36) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.class_2797.method_11054(class_2797.java:9) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:144) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:761) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:155) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:118) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:743) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:737) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:103) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:721) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bcm000$modifiedRunLoop(MinecraftServer.java:5819) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:651) ~[intermediary-server_1.16.5.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[intermediary-server_1.16.5.jar:?]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[21:24:03] [Server thread/ERROR]: This crash report has been saved to: C:\media\mx500\GALAXY\Services\Daemon\hitmc\superflat\.\crash-reports\crash-2021-05-16_21.24.03-server.txt
[21:24:03] [Server thread/INFO]: Unregistering com.sk89q.worldedit.fabric.FabricPlatform from WorldEdit
[21:24:03] [Server thread/INFO]: Stopping server
[21:24:03] [Server thread/INFO]: Saving players
[21:24:03] [Server thread/INFO]: Saving worlds
[21:24:03] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[21:24:04] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[21:24:04] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[21:24:04] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:24:04] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[21:24:04] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[21:24:04] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[21:24:04] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[21:24:04] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
```

**Comment by James103** [comment]
Do you have the full list of mods that you have installed? If so, can you please post that list here? There may be a conflict with another mod (including but not limited to WorldEdit).

**Comment by keuin** [comment]
> Do you have the full list of mods that you have installed? If so, can you please post that list here? There may be a conflict with another mod (including but not limited to WorldEdit).

Here is my mod list:

```
BBOutlineReloaded-2.4-1.16.3-fabric.jar
carpet-tis-addition-mc1.16.5-1.17.0+build.557.jar
fabric-api-0.32.5+1.16.jar
fabric-carpet-1.16.5-1.4.36+v210512.jar
kbackup-fabric-1.6.3_mc1.16.4.jar
lithium-fabric-mc1.16.5-0.6.4.jar
phosphor-fabric-mc1.16.3-0.7.1+build.11.jar
worldedit-mod-7.2.4.jar
```

`carpet-tis-addition` is suspectable, I will remove it and run my server again, to see if it still keep crashing.

**Comment by Fallen-Breath** [comment]
As I posted in scicraft discord https://discord.com/channels/211786369951989762/573613501164159016/843694545320804422

In `carpet.helpers.HopperCounter#fromItem`

https://github.com/gnembon/fabric-carpet/blob/be0635de827f189b505c17807a1025b1314b1193/src/main/java/carpet/helpers/HopperCounter.java#L282-L285

The method `net.minecraft.util.registry.SimpleRegistry#containsId` (ye this is what `net.minecraft.class_2348.method_10250` is) may not be safe to use since it's marked as `@Environment(EnvType.CLIENT)` by fabric

**Comment by xiaoshengu** [comment]
> Do you have the full list of mods that you have installed? If so, can you please post that list here? There may be a conflict with another mod (including but not limited to WorldEdit).

I deleted all other mod, but this problem still exists

**Comment by altrisi** [comment]
Try using the build of PR #865 (https://github.com/gnembon/fabric-carpet/actions/runs/851036438), it should fix the issue (get the Artifacts, then from the zip use the one that doesn't have a `-dev` or `-sources` suffix.
