### ISSUE TITLE
Minecraft failed to start, created a crash report instead

### ISSUE THREAD

**Issue by wh0oo** [gnembon/fabric-carpet#889]
I left a fake player logged in before stopping the server, updating to 1.17-pre1, and restarting the server.  

```
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 5/27/21, 5:44 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:967)
	at carpet.script.CarpetEventServer$CallbackList.call(CarpetEventServer.java:228)
	at carpet.script.CarpetEventServer$Event$1.onTick(CarpetEventServer.java:353)
	at carpet.script.CarpetScriptServer.initializeForWorld(CarpetScriptServer.java:147)
	at carpet.CarpetServer.onServerLoadedWorlds(CarpetServer.java:110)
	at net.minecraft.server.MinecraftServer.handler$zep000$serverLoadedWorlds(MinecraftServer.java:3798)
	at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:358)
	at net.minecraft.class_3176.method_3823(class_3176.java:183)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:665)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17 Pre-release 1
	Minecraft Version ID: 1.17-pre1
	Operating System: Linux (amd64) version 4.18.0-240.22.1.el8_3.x86_64
	Java Version: 16.0.1, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1140893696 bytes (1088 MiB) / 1472200704 bytes (1404 MiB) up to 3149922304 bytes (3004 MiB)
	CPUs: 2
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 3700X 8-Core Processor
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 2
	Graphics card #0 name: bochs-drmdrmfb
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: version: 02
	Virtual memory max (MB): 12068.95
	Virtual memory used (MB): 2229.51
	Swap memory total (MB): 6064.00
	Swap memory used (MB): 5.25
	JVM Flags: 0 total; 
	Fabric Mods: 
		carpet: Carpet Mod 1.4.38
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.9.0
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.9.3
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.9.3
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.6
		com_squareup_okhttp3_logging-interceptor: logging-interceptor 3.9.1
		com_squareup_okhttp3_okhttp: okhttp 3.9.1
		com_squareup_okio_okio: okio 1.13.0
		com_vdurmont_emoji-java: emoji-java 5.1.1
		discarpet: Discarpet 1.16.5-1.4.36
		fabric: Fabric API 0.34.8+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b4463a0
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.0.2+a02b4463a0
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.11+9e521e13a0
		fabric-command-api-v1: Fabric Command API (v1) 1.1.1+a02b4463a0
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afaa0
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+a02b4463a0
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.2+a02b4463a0
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+b7ab6121a0
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.10+a02b4463a0
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.1.0+a02b4463a0
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.8+a02b4463a0
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afaa0
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+a02b4463a0
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+a02b4463a0
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab6121a0
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b4463a0
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b4463a0
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afaa0
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.11+b7ab6121a0
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b4463a0
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afaa0
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+b7ab6121a0
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b4463a0
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b4463a0
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.9+a02b4463a0
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b4463a0
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.7+b7ab6121a0
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+a02b4463a0
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.9+75bf7f0fa0
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.4+a02b4463a0
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab6121a0
		fabricloader: Fabric Loader 0.11.3
		io_vavr_vavr: vavr 0.10.1
		java: Java HotSpot(TM) 64-Bit Server VM 16
		lootstrap: Lootstrap 1.1.0
		minecraft: Minecraft 1.17-beta.1
		org_apache_logging_log4j_log4j-api: log4j-api 2.14.1
		org_apache_logging_log4j_log4j-core: log4j-core 2.14.1
		org_javacord_javacord-api: javacord-api 3.1.1
		org_javacord_javacord-core: javacord-core 3.1.1
		org_json_json: json 20170516
	Player Count: 1 / 20; [EntityPlayerMPFake['ColdStatic'/103, l='ServerLevel[V2a]', x=4877.07, y=92.06, z=5195.17]]
	Data Packs: vanilla, file/homes (incompatible), file/RedPack - Quartz Stonecutter.zip, file/RedPack - Fast Redstone Crafting.zip, file/RedPack - Craftable Deepslate Ores.zip, file/RedPack - Red Sandstone to Red Sand.zip, file/RedPack - Red Sandstone Crafting Compatibility.zip, file/RedPack - Wood Stonecutter.zip, file/RedPack - Husk Drops Sand.zip, file/RedPack - Craftable Shulker Shells.zip, file/RedPack - Red Sandstone Stonecutter.zip, file/RedPack - Quartz Crafting Compatibility.zip, file/RedPack - Slab to Full Block.zip, file/RedPack - Craftable Quartz.zip, file/RedPack - Sandstone Stonecutter.zip, file/RedPack - Craftable Nether Warts.zip, file/RedPack - Craftable Bricks.zip, file/RedPack - Sandstone to Sand.zip, file/RedPack - Craftable Sculk Sensor.zip, Fabric Mods, file/ZeroGrief.zip (incompatible), file/join (incompatible), file/CavesAndCliffsPreview.zip
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

**Comment by gnembon** [comment]
You have probably some scarpet apps loaded - can you list them?

**Comment by wh0oo** [comment]
Hello Gnembon, yes of course!

discordbot.sc  (discord bot script)
discord.sc	(shows link to discord)
dragoneggrespawns.sc (dragon respawns egg)
drop_heads.sc (players might drop heads)
market.sc (shows link to market area)
morewanderingtrades.sc (more wandering trades)
rtp.sc (random teleport)
rules.sc (shows the rules and news to players)
vanish.sc (vanish aned unvanish)
waypoint.sc (waypoints for ops only tesdting right now)
welcome.sc (shows welcome message when players joins)

**Comment by gnembon** [comment]
can you pack them up to one zip file if you don't mind?

**Comment by wh0oo** [comment]
I apologize profusely.  For some reason I ommitted ONE script above in that list, and when going through the files to send you I see that that is the script responsible for the fake player relogging on after a server restart (which is where I had trouble).

The script is called keepalive.sc.  I tried to find the repo I got it from but wasnt able to.  Anywhere, here it is.  Obviously this isnt a Carpet issue.  Thanks!!!

```
// re-logs fake players upon server restart
// must need to place it directly in the world scripts folder

__config() -> {'scope' -> 'global'};

__on_server_starts() -> (
   data = load_app_data();
   if (data && data:'players',
      data = parse_nbt(data:'players');
      for (data,
         for([str('player %s spawn at %f %f %f facing %f %f in %s',
                  _:'name', _:'x', _:'y', _:'z', _:'yaw', _:'pitch', _:'dim'),
              str('gamemode %s %s', _:'gm', _:'name')],
            logger('warn', _);
            run(_);
         )
      )
   );
);

__on_server_shuts_down() -> (
   data = nbt('{players:[]}');
   saved = [];
   for (filter(player('all'), _~'player_type' == 'fake'),
      pdata = nbt('{}');
      pdata:'name' = _~'name';
      pdata:'dim' = _~'dimension';
      pdata:'x' = _~'x';
      pdata:'y' = _~'y';
      pdata:'z' = _~'z';
      pdata:'yaw' = _~'yaw';
      pdata:'pitch' = _~'pitch';
      pdata:'gm' = _~'gamemode';
      put(data, 'players', pdata, -1);
      saved += _~'name';
   );
   store_app_data(data);
   if (saved, logger('warn', 'saved '+saved+' for next startup'));
);
```

**Comment by gnembon** [comment]
try on 1.4.39 - I change a bunch of stuff with scripts and server loading, so that might have fixed it.
